### ISSUE TITLE
Facebook group scraper fails with 'Code container ID marker not found (does the group exist?)'

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#121]
All Facebook group scrapes (that I've tried, e.g. 22137638452 and ACTWP) fail with

    snscrape.base.ScraperException: Code container ID marker not found (does the group exist?)

This is due to Facebook rolling out their new design on group pages.

**Comment by zhixideyu** [comment]
It doesn't work, does it

**Comment by JustAnotherArchivist** [comment]
@zhixideyu It does not. That's why it's marked as a bug and says that it fails with an exception...

**Comment by gitshrl** [comment]
#129 works for me

**Comment by elig0n** [comment]
Still not working

**Comment by JustAnotherArchivist** [comment]
Indeed, this broke again. It looks like Facebook removed the old design from that alternative domain, which was only a matter of time of course.

**Comment by houhashv** [comment]
still not working

**Comment by danishroohul** [comment]
Any idea if there is a workaround for this error?

**Comment by shubhamcodez** [comment]
Any progress on this yet?

**Comment by leonhma** [comment]
same here:

```
processing facebook group HotStocks1
Traceback (most recent call last):
  File "/mnt/c/Users/leonh/Documents/akyth-documents-download/program.py", line 269, in <module>
    process_facebook_groups(group, check_queue, check_length)
  File "/mnt/c/Users/leonh/Documents/akyth-documents-download/program.py", line 196, in process_facebook_groups
    for i, post in enumerate(scraper.get_items()):
  File "/home/leonhardmasche/miniconda3/lib/python3.9/site-packages/snscrape/modules/facebook.py", line 325, in get_items
    raise snscrape.base.ScraperException('Code container ID marker not found (does the group exist?)')
snscrape.base.ScraperException: Code container ID marker not found (does the group exist?)
```

**Comment by Lautaro-Silva** [comment]
Hey, i have just encountered the same error:

> snscrape --jsonl --max-results 100 facebook-group 220337878140555 >face
2023-06-29 19:05:21.661  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_d1b2e7zt
Traceback (most recent call last):
  File "/home/lautaro/.local/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/home/lautaro/.local/lib/python3.10/site-packages/snscrape/_cli.py", line 323, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/lautaro/.local/lib/python3.10/site-packages/snscrape/modules/facebook.py", line 326, in get_items
    raise snscrape.base.ScraperException('Code container ID marker not found (does the group exist?)')
snscrape.base.ScraperException: Code container ID marker not found (does the group exist?)

Is this a problem of the input i am giving it? Is there a workaround?

**Comment by bishalnepali** [comment]
Not working still :)?
