### ISSUE TITLE
instagram: JSONDecodeError

### ISSUE THREAD

**Issue by jodizzle** [JustAnotherArchivist/snscrape#22]
In two separate occasions across a couple thousand Instagram users, I've come across some sort of JSON error:

Case 1:

```
Traceback (most recent call last):
  File "/home/user/bin/snscrape_process.py", line 53, in <module>
    main()
  File "/home/user/bin/snscrape_process.py", line 47, in main
    for post in posts:
  File "/home/user/bin/snscrape_process.py", line 38, in get_posts
    for item in scraper.get_items():
  File "/home/user/snscrape/snscrape/modules/instagram.py", line 61, in get_items
    response = json.loads(r.text)
  File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 37597 (char 37596)
```

Case 2:
```
Traceback (most recent call last):
  File "/home/user/bin/snscrape_process.py", line 53, in <module>
    main()
  File "/home/user/bin/snscrape_process.py", line 47, in main
    for post in posts:
  File "/home/user/bin/snscrape_process.py", line 38, in get_posts
    for item in scraper.get_items():
  File "/home/user/snscrape/snscrape/modules/instagram.py", line 35, in get_items
    response = json.loads(jsonData)
  File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/.pyenv/versions/3.7.0/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 29228 (char 29227)
```
(In the tracebacks, `snscrape_process.py` is the custom script I'm running snscrape from, i.e., I'm not using the CLI directly.)

I'm not sure how reproducible these issues are.  A quick test makes it seem like not very.

If it helps, I can share the particular accounts I was scraping from and/or the logs (I was logging at INFO level).

**Comment by jodizzle** [comment]
Nope, doesn't seem like it's reproducible.  I was able to re-scrape the affected accounts just fine.

(Looking it over, I was slightly wrong: there were actually five cases where this issue came up.  All were the same variety of error, only notable difference was one had an "Expecting value" error message instead of an "Unterminated string" error message.)

**Comment by JustAnotherArchivist** [comment]
Not fully fixed yet. The crash can still occur if the initial web page contains invalid JSON. I just had such a case (not reproducible). Unfortunately, the locals dumper didn't dump the full HTML (because that's inside the Response object and not a local variable directly), so I don't know what exactly happened there.

**Comment by arfathyahiya** [comment]
So I came across the same issue 
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
This apparently appears when the response is in HTML format after reading the response from 
`self._read_response(res)`
it appears rarely but when it shows up it doesn't go for like hours

**Comment by JustAnotherArchivist** [comment]
Hmm, interesting. That error should always be caught in the callbacks. Do you have a detailed traceback and dump file? (Note that the latter may contain sensitive information, cf. [the corresponding readme section](https://github.com/JustAnotherArchivist/snscrape#issue-reporting).)

I don't know what `_read_response` is supposed to be; it's neither part of snscrape nor of Requests or urllib3 as far as I can see.
