### ISSUE TITLE
Instagram grabber: KeyError for `id`

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#244]
I get this when trying to run the instagram grab:

```
╰─$ snscrape -f "{id}" instagram-user xkcd > iglist.txt
2021-06-30 15:07:23.662  CRITICAL  snscrape.cli  Dumped stack and locals to /tmp/snscrape_locals_uek5iq38
Traceback (most recent call last):
  File "/home/thetechrobo/gs-venv/bin/snscrape", line 10, in <module>
    sys.exit(main())
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/snscrape/cli.py", line 235, in main
    print(args.format.format(**item._asdict()))
KeyError: 'id'
```

Here is the contents of the mentioned file:

```
Exception:
  builtins.KeyError: 'id'
  args: ('id',)

Stack:
  File "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/snscrape/cli.py", line 235, in main
    print(args.format.format(**item._asdict()))

Locals from file "/home/thetechrobo/gs-venv/lib/python3.7/site-packages/snscrape/cli.py", line 235, in main:
  args <class 'argparse.Namespace'> = Namespace(cls=<class 'snscrape.modules.instagram.InstagramUserScraper'>, dumpLocals=False, format='{id}', maxResults=None, retries=3, scraper='instagram-user', since=None, username='xkcd', verbosity=0)
  scraper <class 'snscrape.modules.instagram.InstagramUserScraper'> = <snscrape.modules.instagram.InstagramUserScraper object at 0x7e34b6b567f0>
  i <class 'int'> = 1
  item <class 'snscrape.modules.instagram.InstagramPost'> = InstagramPost(cleanUrl='https://www.instagram.com/p/CQtojKnsVGs/', dirtyUrl='https://www.instagram.com/p/CQtojKnsVGs/?taken-by=xkcd', date=datetime.datetime(2021, 6, 29, 17, 47, 56, tzinfo=datetime.timezone.utc), content='Indoor Socializing.\n\nThe problem with learning about biology is that everyone you meet is it.', thumbnailUrl='https://instagram.fybz2-1.fna.fbcdn.net/v/t51.2885-15/sh0.08/e35/s640x640/209006998_810369899664433_2121977623727256143_n.jpg?tp=1&_nc_ht=instagram.fybz2-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=hjhGE3UJ8jMAX_bt6uL&edm=ABfd0MgBAAAA&ccb=7-4&oh=4abb7efbd4b27af91073c755521e937a&oe=60E46FD4&_nc_sid=7bff83', displayUrl='https://instagram.fybz2-1.fna.fbcdn.net/v/t51.2885-15/e35/209006998_810369899664433_2121977623727256143_n.jpg?tp=1&_nc_ht=instagram.fybz2-1.fna.fbcdn.net&_nc_cat=101&_nc_ohc=hjhGE3UJ8jMAX_bt6uL&edm=ABfd0MgBAAAA&ccb=7-4&oh=92cc7bbd53bf64dd935c43bbe0b1d166&oe=60E36BAA&_nc_sid=7bff83', username='xkcd', likes=12056, comments=41, commentsDisabled=False, isVideo=False)
```

This may be caused by a change a while ago where they removed the ID from the results? I remember reading that somewhere on the AT wiki.

**Comment by JustAnotherArchivist** [comment]
There has never been an `id` field on `InstagramPost`, so that's correct.

**Comment by TheTechRobo** [comment]
Wait but then how did that happen?

**Comment by JustAnotherArchivist** [comment]
Because you specified an inexistent field in the `--format` option. `--format '{thisdoesnotexist}'` would cause the exact same error.

The fields are different for each scraper and currently not documented; check the definition of `InstagramPost` in `snscrape/modules/instagram.py` for the available fields.

**Comment by TheTechRobo** [comment]
Ohhh, that would make sense! Sorry - I thought it was a problem in the scraper.
