### ISSUE TITLE
`KeyError: 'url'` in `_user_to_user` on scraping Twitter

### ISSUE THREAD

**Issue by topliftarm** [JustAnotherArchivist/snscrape#281]
when using snscrape for collect data, this error appear:

```
Traceback (most recent call last):
  File "/root/anaconda3/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/lib/python3.8/site-packages/snscrape/_cli.py", line 280, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/root/anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 527, in get_items
    yield from self._instructions_to_tweets(obj)
  File "/root/anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 306, in _instructions_to_tweets
    yield from self._instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
  File "/root/anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 329, in _instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)
  File "/root/anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 390, in _tweet_to_tweet
    kwargs['quotedTweet'] = self._tweet_to_tweet(obj['globalObjects']['tweets'][tweet['quoted_status_id_str']], obj)
  File "/root/anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 337, in _tweet_to_tweet
    kwargs['user'] = self._user_to_user(obj['globalObjects']['users'][tweet['user_id_str']])
  File "/root/anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 464, in _user_to_user
    kwargs['labelUrl'] = user['ext']['highlightedLabel']['r']['ok']['label']['url']['url']
KeyError: 'url'
```

**Comment by JustAnotherArchivist** [comment]
Interesting. Please provide details on your crawl and, if possible, the dump file.

**Comment by topliftarm** [comment]
query : 
snscrape --jsonl twitter-search near:nyc since:2021-09-19 until:2021-09-20 include:nativeretweets

**Comment by JustAnotherArchivist** [comment]
Found the tweet causing the crash: `snscrape twitter-tweet 1439740713672060928`

Looks like this is caused by a new Twitter feature that's currently being tested: https://twitter.com/TwitterSupport/status/1436073604173770754

Will fix this later.
