### ISSUE TITLE
Regarding usage of TwitterTweetScraper

### ISSUE THREAD

**Issue by raza8899** [JustAnotherArchivist/snscrape#291]
@JustAnotherArchivist 
I want to get details of a specific tweet and for that I am passing tweet_id, but the function expects a mode parameter as well.
I would be really thankful if you can describe what values does this parameter takes.

`
Usage Python:
tweet =sntwitter.TwitterTweetScraper(tweet_id,mode=).get_item()
`

**Comment by raza8899** [comment]
Okay thanks for the answer @JustAnotherArchivist 

But even if I run the below code I didn't get any response


```
import snscrape.modules.twitter as sntwitter
import json

def get_specific_tweet(tweet_id):
    print(tweet_id)
    tweets_list = []
    for i,tweet in enumerate(sntwitter.TwitterTweetScraper(tweetId="1447871903075557377",mode='single').get_items()):
        print(tweet)
        return json.loads(tweet.json())

```

Can you please tell me what's wrong in the above code or does the TwitterTweetScraper doesn't work with python?

**Comment by baburz** [comment]
I'm new to snscrape and  got an error while using the above code, AttributeError: 'str' object has no attribute 'read'. Print statement prints a URL. Also when the tweet is deleted or sth, for loop stops. Does anyone have an idea how can i overcome those issues?

**Comment by TheTechRobo** [comment]
To clarify, you're using [this comment](https://github.com/JustAnotherArchivist/snscrape/issues/291#issuecomment-941119534), right?

**Comment by qublaidev** [comment]
```
def get_replies_to_spesific_tweet(tweet_id):
    replies_list = []
    # Using TwitterSearchScraper to scrape data and append tweets to list

    for i, tweet in enumerate(sntwitter.TwitterTweetScraper(tweetId=tweet_id, mode=sntwitter.TwitterTweetScraperMode.RECURSE, ).get_items()):
        try:
            data = [tweet.id, tweet.rawContent, tweet.user.username]
        except:    # this exception is here to catch Tombstone object errors
            print("error")

        replies_list.append(data)
    return replies_list 
```

this above code works to some degree and then results in below error: GenericError: _Missing: No status found with that ID.

```
Error retrieving https://twitter.com/i/api/graphql/miKSMGb2R1SewIJv2-ablQ/TweetDetail?variables=%7B%22focalTweetId%22%3A%221671199177756274688%22%2C%22cursor%22%3Anull%2C%22referrer%22%3A%22tweet%22%2C%22with_rux_injections%22%3Afalse%2C%22includePromotedContent%22%3Atrue%2C%22withCommunity%22%3Atrue%2C%22withQuickPromoteEligibilityTweetFields%22%3Atrue%2C%22withBirdwatchNotes%22%3Afalse%2C%22withVoice%22%3Atrue%2C%22withV2Timeline%22%3Atrue%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Atrue%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Atrue%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%7D: Twitter responded with an error: GenericError: _Missing: No status found with that ID.
4 requests to https://twitter.com/i/api/graphql/miKSMGb2R1SewIJv2-ablQ/TweetDetail?variables=%7B%22focalTweetId%22%3A%221671199177756274688%22%2C%22cursor%22%3Anull%2C%22referrer%22%3A%22tweet%22%2C%22with_rux_injections%22%3Afalse%2C%22includePromotedContent%22%3Atrue%2C%22withCommunity%22%3Atrue%2C%22withQuickPromoteEligibilityTweetFields%22%3Atrue%2C%22withBirdwatchNotes%22%3Afalse%2C%22withVoice%22%3Atrue%2C%22withV2Timeline%22%3Atrue%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Atrue%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Atrue%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%7D failed, giving up.
Errors: Twitter responded with an error: GenericError: _Missing: No status found with that ID., Twitter responded with an error: GenericError: _Missing: No status found with that ID., Twitter responded with an error: GenericError: _Missing: No status found with that ID., Twitter responded with an error: GenericError: _Missing: No status found with that ID.
Traceback (most recent call last):
  File "C:\Users\pttsb\Downloads\twitter-scrape\scraper.py", line 41, in <module>
    a = get_replies_to_spesific_tweet(1671181155838599174)
  File "C:\Users\pttsb\Downloads\twitter-scrape\scraper.py", line 11, in get_replies_to_spesific_tweet
    for i, tweet in enumerate(sntwitter.TwitterTweetScraper(tweetId=tweet_id, mode=sntwitter.TwitterTweetScraperMode.RECURSE).get_items()):
  File "C:\Users\pttsb\AppData\Local\Programs\Python\Python310\lib\site-packages\snscrape\modules\twitter.py", line 2009, in get_items
    for obj in self._iter_api_data(url, _TwitterAPIType.GRAPHQL, thisParams, thisPagParams, direction = _ScrollDirection.BOTH, instructionsPath = instructionsPath):
  File "C:\Users\pttsb\AppData\Local\Programs\Python\Python310\lib\site-packages\snscrape\modules\twitter.py", line 876, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams, instructionsPath = instructionsPath)
  File "C:\Users\pttsb\AppData\Local\Programs\Python\Python310\lib\site-packages\snscrape\modules\twitter.py", line 847, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = functools.partial(self._check_api_response, apiType = apiType, instructionsPath = instructionsPath))
  File "C:\Users\pttsb\AppData\Local\Programs\Python\Python310\lib\site-packages\snscrape\base.py", line 272, in _get
    return self._request('GET', *args, **kwargs)
  File "C:\Users\pttsb\AppData\Local\Programs\Python\Python310\lib\site-packages\snscrape\base.py", line 268, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://twitter.com/i/api/graphql/miKSMGb2R1SewIJv2-ablQ/TweetDetail?variables=%7B%22focalTweetId%22%3A%221671199177756274688%22%2C%22cursor%22%3Anull%2C%22referrer%22%3A%22tweet%22%2C%22with_rux_injections%22%3Afalse%2C%22includePromotedContent%22%3Atrue%2C%22withCommunity%22%3Atrue%2C%22withQuickPromoteEligibilityTweetFields%22%3Atrue%2C%22withBirdwatchNotes%22%3Afalse%2C%22withVoice%22%3Atrue%2C%22withV2Timeline%22%3Atrue%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Atrue%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Atrue%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%7D failed, giving up.
```

the tweet is not deleted or anything but after 400+ tweets this error occurs

**Comment by TheTechRobo** [comment]
What tweet id is it?

**Comment by qublaidev** [comment]
it's just some politician from Turkey
https://twitter.com/kilicdarogluk/status/1671181155838599174

**Comment by qublaidev** [comment]
and by the way what is the correct way of getting all the replies of a tweet?
I used scroll mode but it only got ~200 replies back

**Comment by JustAnotherArchivist** [comment]
@qublaidev That has nothing to do with this issue; please file a separate complete bug report instead.
