### ISSUE TITLE
snscrape.base.ScraperException: Unable to find guest token

### ISSUE THREAD

**Issue by kwekuobosu** [JustAnotherArchivist/snscrape#350]
My application on a Linode server started throwing this exception a few days ago, prior to that it was working just fine. It is somewhat intermittent because on some occasions it returns the required data. My initial thought was maybe the IP was blocked but it's the same situation from my local shell. I tried on both **production** and **development** versions

### Development
```
snscrape --max-results 100 twitter-search "from:jack" > user-tweets.json
2022-01-07 01:26:03.655  CRITICAL  snscrape.cli  Dumped stack and locals to /var/folders/wv/xjtt82w979q4lsn3ndz91dxh0000gn/T/snscrape_locals_znsvk_h0
Traceback (most recent call last):
  File "/.../bin/snscrape", line 10, in <module>
    sys.exit(main())
  File "/.../lib/python3.7/site-packages/snscrape/cli.py", line 230, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/.../lib/python3.7/site-packages/snscrape/modules/twitter.py", line 131, in get_items
    guestToken = self._get_guest_token()
  File "/.../lib/python3.7/site-packages/snscrape/modules/twitter.py", line 109, in _get_guest_token
    raise snscrape.base.ScraperException('Unable to find guest token')
snscrape.base.ScraperException: Unable to find guest token
```
### Production
 ```
 File "/../lib/python3.9/site-packages/snscrape/modules/twitter.py", line 556, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/../lib/python3.9/site-packages/snscrape/modules/twitter.py", line 250, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/../lib/python3.9/site-packages/snscrape/modules/twitter.py", line 219, in _get_api_data
    self._ensure_guest_token()
  File "/.../lib/python3.9/site-packages/snscrape/modules/twitter.py", line 200, in _ensure_guest_token
    raise snscrape.base.ScraperException('Unable to find guest token')
snscrape.base.ScraperException: Unable to find guest token
```

**Comment by TheTechRobo** [comment]
Are you using the latest version^ Twitter recently changed the way guest tokens are retrived; the latest release fixes that.

```
python3.9 -m pip install --upgrade snscrape
```

**Comment by JustAnotherArchivist** [comment]
This has been fixed. Please install the current version of snscrape, released yesterday.

**Comment by kwekuobosu** [comment]
Installed the current version and it's all good now. Thank you @TheTechRobo @JustAnotherArchivist. Appreciate the good work @JustAnotherArchivist .

**Comment by TheTechRobo** [comment]
Maybe you(JustAnotherArchivist) should add a prominent notice about this in the README, so this doesn't keep happening. :thinking:

Something like

```markdown
### If you're getting `Unable to find guest token` in the twitter scraper
If you receive the error `Unable to find guest token` in the Twitter scraper, please make sure snscrape is up to date. Try `pip install --upgrade snscrape`.
```

**Comment by JustAnotherArchivist** [comment]
I've pinned #347, let's hope that's sufficient.
