### ISSUE TITLE
twitter-tweet: `KeyError: bounding_box` on 919265494347137024

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#374]
<details><summary>Traceback</summary>

```
2022-01-29 14:13:49.022  INFO  snscrape.modules.twitter  Retrieving guest token
2022-01-29 14:13:49.023  INFO  snscrape.base  Retrieving https://twitter.com/i/web/919265494347137024
2022-01-29 14:13:49.685  INFO  snscrape.base  Retrieved https://twitter.com/i/web/919265494347137024: 200
2022-01-29 14:13:49.686  INFO  snscrape.base  Retrieving https://twitter.com/i/api/2/timeline/conversation/919265494347137024.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=20&include_ext_has_birdwatch_notes=false&ext=mediaStats%2ChighlightedLabel
2022-01-29 14:13:50.351  INFO  snscrape.base  Retrieved https://twitter.com/i/api/2/timeline/conversation/919265494347137024.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweet=true&count=20&include_ext_has_birdwatch_notes=false&ext=mediaStats%2ChighlightedLabel: 200
2022-01-29 14:13:50.368  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_od3iuck6
Traceback (most recent call last):
  File "/home/thetechrobo/.local/bin/snscrape", line 33, in <module>
    sys.exit(load_entry_point('snscrape==0.3.5.dev138+ga6b6f3f', 'console_scripts', 'snscrape')())
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/_cli.py", line 283, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 763, in get_items
    yield self._tweet_to_tweet(obj['globalObjects']['tweets'][str(self._tweetId)], obj)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 406, in _tweet_to_tweet
    kwargs['quotedTweet'] = self._tweet_to_tweet(obj['globalObjects']['tweets'][tweet['quoted_status_id_str']], obj)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 432, in _tweet_to_tweet
    if 'coordinates' not in kwargs and tweet['place']['bounding_box'] and (coords := tweet['place']['bounding_box']['coordinates']) and coords[0] and len(coords[0][0]) == 2:
KeyError: 'bounding_box'
```

</details>

Locals: http://sprunge.us/Wz4buM

**Comment by TheTechRobo** [comment]
Noticed that my snscrape was outdated af so I updated to the dev version; same problem.

**Comment by JustAnotherArchivist** [comment]
The offending tweet is actually 919247154199216129, and its data is pretty weird:

```
          obj['globalObjects']['tweets']['919247154199216129']['place'] = <builtins.dict>
            obj['globalObjects']['tweets']['919247154199216129']['place']['id'] = '07d9ca9f84884001'
            obj['globalObjects']['tweets']['919247154199216129']['place']['url'] = 'https://api.twitter.com/1.1/geo/id/07d9ca9f84884001.json'
            obj['globalObjects']['tweets']['919247154199216129']['place']['place_type'] = 'poi'
            obj['globalObjects']['tweets']['919247154199216129']['place']['name'] = '[Place name removed]'
            obj['globalObjects']['tweets']['919247154199216129']['place']['full_name'] = '[Place name removed]'
            obj['globalObjects']['tweets']['919247154199216129']['place']['country_code'] = ''
            obj['globalObjects']['tweets']['919247154199216129']['place']['country'] = ''
            obj['globalObjects']['tweets']['919247154199216129']['place']['contained_within'] = []
            obj['globalObjects']['tweets']['919247154199216129']['place']['attributes'] = <builtins.dict>
```

But fixing it is trivial, commit coming shortly.

**Comment by TheTechRobo** [comment]
Thanks, I can now continue my scrape
