### ISSUE TITLE
429 in twitter-profile scraper

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#375]
```
2022-01-29 15:04:04.202  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/timeline/profile/905019092.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&include_tweet_replies=true&userId=905019092&count=100&ext=mediaStats%2ChighlightedLabel: blocked (429)
2022-01-29 15:04:04.202  CRITICAL  snscrape.base  4 requests to https://api.twitter.com/2/timeline/profile/905019092.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&include_tweet_replies=true&userId=905019092&count=100&ext=mediaStats%2ChighlightedLabel failed, giving up.
2022-01-29 15:04:04.216  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_srarqx00
Traceback (most recent call last):
  File "/home/thetechrobo/.local/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 813, in get_items
    for obj in self._iter_api_data(f'https://api.twitter.com/2/timeline/profile/{userId}.json', params, paginationParams):
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/base.py", line 218, in _get
    return self._request('GET', *args, **kwargs)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/base.py", line 214, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/timeline/profile/905019092.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&include_tweet_replies=true&userId=905019092&count=100&ext=mediaStats%2ChighlightedLabel failed, giving up.
```
works in browser and twitter-user

Dump: http://sprunge.us/dy3OPI

**Comment by TheTechRobo** [comment]
keep in mind this happened about a week ago too but I pegged it off as me having multiple concurrent scrapes

**Comment by TheTechRobo** [comment]
oops, dupe of #367, sorry
