### ISSUE TITLE
AttributeError: 'TwitterSearchScraper' object has no attribute '_instruction_tweet_entry_to_tweet'

### ISSUE THREAD

**Issue by topliftarm** [JustAnotherArchivist/snscrape#393]
i have problem:
query:  snscrape --jsonl twitter-search near:cityName since:date1  until:date2 include:nativeretweets > fileName

out:
2022-02-08 07:51:46.059  CRITICAL  snscrape._cli  Dumped stack and locals to snscrape_locals_6isfr4t_
Traceback (most recent call last):
  File "anaconda3/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "anaconda3/lib/python3.8/site-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 755, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)
  File "anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 470, in _v2_timeline_instructions_to_tweets
    yield from self._instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
AttributeError: 'TwitterSearchScraper' object has no attribute '_instruction_tweet_entry_to_tweet'

**Comment by wbaker23** [comment]
Fix PR is up for review @JustAnotherArchivist
