### ISSUE TITLE
KeyError: 'legacy' when scraping recursively on 1450493209180770307

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#400]
```
/m/t/2/t/bbc ❯❯❯ s twitter-tweet --recurse 1450493209180770307
https://twitter.com/BBCAfrica/status/1450493209180770307
https://twitter.com/RepublikFree/status/1450495061091917829
https://twitter.com/tesfanews/status/1450500146643472384
https://twitter.com/Mikiadiss/status/1450504895388426245
https://twitter.com/Berted5/status/1450505657816395783
https://twitter.com/RomanMDebotch/status/1450511198005256192
https://twitter.com/cFkGZDMYPxhhCJK/status/1450516086860836864
https://twitter.com/zmedhanie13/status/1450512171809615875
https://twitter.com/FTigrai/status/1450519529566740487
https://twitter.com/EremiasWmikael/status/1450519082995003394
https://twitter.com/Yordano32442465/status/1450528702052376579
https://twitter.com/Harenet1993/status/1450529941620203525
https://twitter.com/arag9105/status/1450530135912898566
https://twitter.com/HENOKBEL/status/1450538493986414592
https://twitter.com/HazWedi/status/1450539358466027533
https://twitter.com/Jordita6/status/1450542196814385158
https://twitter.com/Aksum_99/status/1450545293108334603
https://twitter.com/___rikh/status/1450544350153396230
2022-02-11 10:58:03.375  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_b_7ni7ox
Traceback (most recent call last):
  File "/home/thetechrobo/.local/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 978, in get_items
    for tweet in self._graphql_timeline_instructions_to_tweets(obj['data']['threaded_conversation_with_injections']['instructions'], includeConversationThreads = True):
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 636, in _graphql_timeline_instructions_to_tweets
    yield self._graphql_timeline_tweet_item_result_to_tweet(item['item']['itemContent']['tweet_results']['result'])
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 604, in _graphql_timeline_tweet_item_result_to_tweet
    tweet = result['legacy']
KeyError: 'legacy'
```
Locals: https://transfer.archivete.am/xGXvh/locals

**Comment by TheTechRobo** [comment]
Is this related to the tombstones issue?
