### ISSUE TITLE
Pyinstaller WinError 3

### ISSUE THREAD

**Issue by Mennaruuk** [JustAnotherArchivist/snscrape#404]
How are you JustAnotherArchivist?

I'm trying to package my script into an executable using pyInstaller. It succeeds in making the executable. However, the executable does not run well.

It gets the following error when I run it:
```

Traceback (most recent call last):
  File "twayback.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "snscrape\modules\__init__.py", line 15, in <module>
  File "snscrape\modules\__init__.py", line 7, in _import_modules
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Menna\\AppData\\Local\\Temp\\_MEI84722\\snscrape\\modules'

```
I tried making a copy of snscrape and the folder modules inside it and place it in the TEMP directory above, but that didn't work.

This looks very similar to #357.

Do you know what I can change in the file _init__.py so that I can have the system successfully find snscrape and modules?

Thank you so much for your help. You are awesome.

**Comment by Mennaruuk** [comment]
Thank you so much. This worked amazingly. I also tried the solution outlined [here](https://github.com/JustAnotherArchivist/snscrape/issues/357#issuecomment-1012595679), but that's essentially the same.

I hope you have a great day and year.
