### ISSUE TITLE
new problem !

### ISSUE THREAD

**Issue by topliftarm** [JustAnotherArchivist/snscrape#409]
query:
!snscrape --jsonl twitter-search My_Query  since:date1  until:date2> report.jsonl

result:
snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_objvoaz_
Traceback (most recent call last):
  File ".... anaconda3/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File .... anaconda3/lib/python3.8/site-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File ".... anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 805, in get_items
    yield from self._v2_timeline_instructions_to_tweets(obj)
  File "..... anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 483, in _v2_timeline_instructions_to_tweets
    yield from self._v2_instruction_tweet_entry_to_tweet(entry['entryId'], entry['content'], obj)
  File "..... anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 506, in _v2_instruction_tweet_entry_to_tweet
    yield self._tweet_to_tweet(tweet, obj)
  File "..... anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 638, in _tweet_to_tweet
    kwargs['card'] = self._make_card(tweet['card'], _TwitterAPIType.V2)
  File "..... anaconda3/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 628, in _make_card
    return Card(**cardKwargs)
TypeError: __init__() missing 1 required positional argument: 'title'

**Comment by JustAnotherArchivist** [comment]
Thanks, merging this with #407
