### ISSUE TITLE
Twitter: "RuntimeError: Unable to find min-position" for empty users

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#41]
Example: https://twitter.com/Eric_Andrieu

    Traceback (most recent call last):
      File ".../bin/snscrape", line 11, in <module>
        load_entry_point('snscrape', 'console_scripts', 'snscrape')()
      File ".../snscrape/cli.py", line 111, in main
        for i, item in enumerate(scraper.get_items(), start = 1):
      File ".../snscrape/modules/twitter.py", line 99, in get_items
        feed, maxPosition = self._get_feed_from_html(r.text, True)
      File ".../snscrape/modules/twitter.py", line 40, in _get_feed_from_html
        raise RuntimeError('Unable to find min-position')
    RuntimeError: Unable to find min-position

**Comment by JustAnotherArchivist** [comment]
This also happens for users which are affected by #4.
