### ISSUE TITLE
t.co URL replacement does not work on retweeted cards

### ISSUE THREAD

**Issue by abtGIT** [JustAnotherArchivist/snscrape#411]
```
File ".../lib/python3.9/site-packages/snscrape/modules/twitter.py", line 931, in get_items
    yield from self._graphql_timeline_instructions_to_tweets(instructions)
  File ".../lib/python3.9/site-packages/snscrape/modules/twitter.py", line 676, in _graphql_timeline_instructions_to_tweets
    yield self._graphql_timeline_tweet_item_result_to_tweet(entry['content']['itemContent']['tweet_results']['result'])
  File ".../lib/python3.9/site-packages/snscrape/modules/twitter.py", line 667, in _graphql_timeline_tweet_item_result_to_tweet
    return self._make_tweet(tweet, user, **kwargs)
  File "..../lib/python3.9/site-packages/snscrape/modules/twitter.py", line 605, in _make_tweet
    i = kwargs['tcooutlinks'].index(card.url)
KeyError: 'tcooutlinks'
```

**Comment by TheTechRobo** [comment]
Do you know what tweet it's failing on? If not, what is the command you're running?

**Comment by abtGIT** [comment]
For many scenarios it's working, however for some tweets for example the below one fails:

https://twitter.com/RealZainTv/status/1495128319641149445

with the following stack trace

2022-02-22 11:36:06.932 Traceback (most recent call last):
  File "...", line 346, in ..
    for i,tweet in enumerate(tweets.get_items()):
  File ".../python3.9/site-packages/snscrape/modules/twitter.py", line 931, in get_items
    yield from self._graphql_timeline_instructions_to_tweets(instructions)
  File ".../python3.9/site-packages/snscrape/modules/twitter.py", line 676, in _graphql_timeline_instructions_to_tweets
    yield self._graphql_timeline_tweet_item_result_to_tweet(entry['content']['itemContent']['tweet_results']['result'])
  File ".../python3.9/site-packages/snscrape/modules/twitter.py", line 667, in _graphql_timeline_tweet_item_result_to_tweet
    return self._make_tweet(tweet, user, **kwargs)
  File ".../python3.9/site-packages/snscrape/modules/twitter.py", line 605, in _make_tweet
    i = kwargs['tcooutlinks'].index(card.url)
KeyError: 'tcooutlinks'

**Comment by JustAnotherArchivist** [comment]
Thanks. I'm pretty sure 1495127220460810241 is the tweet that causes the crash. That would be the same problem I also saw while working on a proper resolution of #407 a few days ago, albeit for a slightly different reason. It's an edge case on retweets. It's mostly fixed in my local uncommitted code. Specifically, it doesn't crash, but the translation of t.co URLs to full URLs doesn't work correctly. I'll turn this into an issue for handling that edge case.

**Comment by darentanrw** [comment]
Hi there! Was just wondering is there any update on this? Is it possible for there to be another dev branch on this repo with your current local uncommitted code? Thanks!

**Comment by JustAnotherArchivist** [comment]
See the last comment on the issue linked above, as these two are closely related. If you need it working *now*, I'd suggest installing either the release version or the commit before I added card extraction last week.
