### ISSUE TITLE
Twitter scraper seems to remove the guest-token persistence file not caring for the file lock?

### ISSUE THREAD

**Issue by TheTechRobo** [JustAnotherArchivist/snscrape#414]
That just happened for me. I've been running a bunch of simultaneous crawls...

```
Scraping, 188600 results so far
2022-02-25 19:44:59.162  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_ina_flsu            
Traceback (most recent call last):
  File "/home/thetechrobo/.local/bin/snscrape", line 8, in <module>                                                   
    sys.exit(main())
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/_cli.py", line 308, in main                     
    for i, item in enumerate(scraper.get_items(), start = 1):                                                         
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 680, in get_items     
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 339, in _get_api_data 
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/base.py", line 216, in _get                     
    return self._request('GET', *args, **kwargs)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/base.py", line 189, in _request                 
    success, msg = responseOkCallback(r)
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 328, in _check_api_response
    self._unset_guest_token()
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 322, in _unset_guest_token
    self._guestTokenManager.reset()
  File "/home/thetechrobo/.local/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 267, in reset         
    os.remove(self._file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/thetechrobo/.cache/snscrape/cli-twitter-guest-token.json'
```

Not sure if it's reproducible.

**Comment by JustAnotherArchivist** [comment]
Thanks. I'm pretty sure it's this race condition: if one process resets the token manager and then a second one does so as well before the first one writes the file again, the second one will crash. In most cases, the new token gets retrieved quickly enough, so the second reset will simply delete the file again. Of course, it would be even better if the second process would just wait for the first's token to become available, but implementing that without the potential for deadlocks if the first process crashes or gets killed is tricky, which is why I decided against that. But I didn't think of this race condition on the removal.

**Comment by TheTechRobo** [comment]
Couldn't you wrap it in a `try` block and if there's a FileNotFoundError you assume someone else has already deleted it and try to read the token from it, or are there technical difficulties about going like that?

**Comment by JustAnotherArchivist** [comment]
Yeah, that's the obvious solution. I was thinking about a better approach as sketched above, but I'm not sure it's worth it. (There are already other potential deadlocks though.)
