### ISSUE TITLE
Query problem?

### ISSUE THREAD

**Issue by haima23** [JustAnotherArchivist/snscrape#476]
Hello:
I need to scrape 5K tweets of Israeli Arab citizens, I tried this query:

```python3
import pandas as pd
import snscrape.modules.twitter as sntwitter
import itertools

loc = '31.5313113, 34.8667654, 250km'
df_coord = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    '@IsraelMOH (كورونا OR كوفيد OR "وزارة الصحة الاسرائيلية") geocode:"{}" since:2020-03-01 until:2020-05-30 '.format(loc)).get_items(), 50))

df_coord['user_location'] =  df_coord['user'].apply(lambda x: x['location'])

df_coord.to_csv('tweetsloc.csv')
```

I get this error:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/haima/Documents/Python/twitter/snscrape/ByLocation.py", line 9, in <module>
    df_coord['user_location'] =  df_coord['user'].apply(lambda x: x['location'])
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/homebrew/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'user'
```

I hope for your help.
Thanks

**Comment by JustAnotherArchivist** [comment]
I can't help you with Pandas questions, but that search query returns no results for me, so I assume that has something to do with it.
