### ISSUE TITLE
Arg construct error for twitter-trends scraper on Windows

### ISSUE THREAD

**Issue by jkswin** [JustAnotherArchivist/snscrape#483]
(Relatively new so apologies if this is a trivial question/issue)

OS: Windows 10 Pro 20H2
Python: 3.8.3 and 3.9.13
snscrape: 0.4.3.20220106

For both Py versions using CLI `snscrape twitter-trends` returns:

`C:\Users\User>snscrape --jsonl --max-results 10 twitter-trends > trends.jsonl
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\snscrape\_cli.py", line 296, in main
    scraper = args.cls.cli_from_args(args)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\snscrape\base.py", line 227, in cli_from_args
    return cls._construct(args)
AttributeError: type object 'TwitterTrendsScraper' has no attribute '_construct'`

Other Twitter scrapers are working fine, it's just the trends scraper that is erroring out.

Thanks in advance!

**Comment by dehma01** [comment]
Hi,

I have the same issue when using  `snscrape twitter-trends`.

**Comment by TheTechRobo** [comment]
Please make sure you're on the latest snscrape version.
