### ISSUE TITLE
snscrape.base.ScraperException: 4 requests to

### ISSUE THREAD

**Issue by sum-sumnee** [JustAnotherArchivist/snscrape#500]
```python3
tweets = []
query = "(elon OR elon_musk OR elonmusk) until:2022-06-25 since:2007-01-01"
for tweet in sntwitter.TwitterSearchScraper(query).get_items():
        tweets.append([tweet.date, tweet.user.username,tweet.user.id,tweet.lang,tweet.content,tweet.coordinates,tweet.place,tweet.likeCount])

df = pd.DataFrame(tweets, columns=['Date', 'User', 'id','lang','Tweet','coordinates','place','likeCount'])
df['Date'] = df['Date'].dt.tz_localize(None)
```

```
/Users//opt/anaconda3/envs/twitter/bin/python "/Users//Desktop/Sentiment on twitter/sen_01.py"
```

```
Error retrieving https://twitter.com/search?f=live&lang=en&q=%28elon+OR+elon_musk+OR+elonmusk%29+until%3A2022-06-25+since%3A2007-01-01&src=spelling_expansion_revert_click: SSLError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /search?f=live&lang=en&q=%28elon+OR+elon_musk+OR+elonmusk%29+until%3A2022-06-25+since%3A2007-01-01&src=spelling_expansion_revert_click (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)')))"))
4 requests to https://twitter.com/search?f=live&lang=en&q=%28elon+OR+elon_musk+OR+elonmusk%29+until%3A2022-06-25+since%3A2007-01-01&src=spelling_expansion_revert_click failed, giving up.
Traceback (most recent call last):
  File "/Users/\/Desktop/Sentiment on twitter/sen_01.py", line 24, in <module>
    for tweet in sntwitter.TwitterSearchScraper(query,cursor = 'scroll:thGAVUV0VFVBakgLOth96DjSoWmsC9pfHBorsqEnEV85sWFYCJehgEVVNFUjUBFYjSARUAAA==').get_items():
  File "/Users/\/opt/anaconda3/envs/twitter/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/Users//opt/anaconda3/envs/twitter/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/Users//opt/anaconda3/envs/twitter/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 338, in _get_api_data
    self._ensure_guest_token()
  File "/Users//opt/anaconda3/envs/twitter/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 301, in _ensure_guest_token
    r = self._get(self._baseUrl if url is None else url, headers = {'User-Agent': self._userAgent}, responseOkCallback = self._check_guest_token_response)
  File "/Users//opt/anaconda3/envs/twitter/lib/python3.10/site-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "/Users//opt/anaconda3/envs/twitter/lib/python3.10/site-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to
```

**Comment by JustAnotherArchivist** [comment]
Are you using a proxy?

**Comment by JustAnotherArchivist** [comment]
@TheTechRobo Indeed. Interesting but unrelated as that happens with curl + warcprox as well. Must be a bug in warcprox.

**Comment by JustAnotherArchivist** [comment]
Then something on your system is broken. Perhaps your CA certificate collection is outdated.
Or the connection gets proxied without your knowledge.
Either way, I don't think this is an issue in snscrape or with Twitter as it works fine for me from three continents.

**Comment by sum-sumnee** [comment]
ok thanks
