### ISSUE TITLE
Error retrieving a Twitter user from a Docker container

### ISSUE THREAD

**Issue by T145** [JustAnotherArchivist/snscrape#536]
The Twitter CLI doesn't seem to working. Here's the stack dump:

```
Exception:
  snscrape.base.ScraperException: 4 requests to https://twitter.com/elonmusk failed, giving up.
  args: ('4 requests to https://twitter.com/elonmusk failed, giving up.',)

Stack:
  File "/usr/local/lib/python3.9/dist-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 753, in get_items
    yield from super().get_items()
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 338, in _get_api_data
    self._ensure_guest_token()
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 301, in _ensure_guest_token
    r = self._get(self._baseUrl if url is None else url, headers = {'User-Agent': self._userAgent}, responseOkCallback = self._check_guest_token_response)
  File "/usr/local/lib/python3.9/dist-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)

Locals from file "/usr/local/lib/python3.9/dist-packages/snscrape/_cli.py", line 308, in main:
  args <class 'argparse.Namespace'> = args = Namespace(citation=None, verbosity=0, dumpLocals=False, retries=3, maxResults=None, format=None, jsonl=False, withEntity=False, since=None, progress=False, scraper='twitter-user', isUserId=False, username='elonmusk', cls=<class 'snscrape.modules.twitter.TwitterUserScraper'>)
  scraper <class 'snscrape.modules.twitter.TwitterUserScraper'> = scraper = <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>
  i <class 'int'> = i = 0

Locals from file "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 753, in get_items:
  self <class 'snscrape.modules.twitter.TwitterUserScraper'> = self = <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>
  __class__ <class 'type'> = __class__ = <class 'snscrape.modules.twitter.TwitterUserScraper'>

Object dict:
{'_retries': 3, '_session': <requests.sessions.Session object at 0x7f77177756a0>, '_baseUrl': 'https://twitter.com/elonmusk', '_guestTokenManager': <snscrape.modules.twitter._CLIGuestTokenManager object at 0x7f77177759a0>, '_apiHeaders': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', 'Authorization': 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA', 'Referer': 'https://twitter.com/search?f=live&lang=en&q=from%3Aelonmusk&src=spelling_expansion_revert_click', 'Accept-Language': 'en-US,en;q=0.5'}, '_userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', '_query': 'from:elonmusk', '_cursor': None, '_top': False, '_username': 'elonmusk', '_isUserId': False}

Locals from file "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 680, in get_items:
  self <class 'snscrape.modules.twitter.TwitterUserScraper'> = self = <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>
  paginationParams <class 'dict'> = paginationParams = <builtins.dict>
    paginationParams['include_profile_interstitial_type'] = '1'
    paginationParams['include_blocking'] = '1'
    paginationParams['include_blocked_by'] = '1'
    paginationParams['include_followed_by'] = '1'
    paginationParams['include_want_retweets'] = '1'
    paginationParams['include_mute_edge'] = '1'
    paginationParams['include_can_dm'] = '1'
    paginationParams['include_can_media_tag'] = '1'
    paginationParams['skip_status'] = '1'
    paginationParams['cards_platform'] = 'Web-12'
    paginationParams['include_cards'] = '1'
    paginationParams['include_ext_alt_text'] = 'true'
    paginationParams['include_quote_count'] = 'true'
    paginationParams['include_reply_count'] = '1'
    paginationParams['tweet_mode'] = 'extended'
    paginationParams['include_entities'] = 'true'
    paginationParams['include_user_entities'] = 'true'
    paginationParams['include_ext_media_color'] = 'true'
    paginationParams['include_ext_media_availability'] = 'true'
    paginationParams['send_error_codes'] = 'true'
    paginationParams['simple_quoted_tweets'] = 'true'
    paginationParams['q'] = 'from:elonmusk'
    paginationParams['tweet_search_mode'] = 'live'
    paginationParams['count'] = '100'
    paginationParams['query_source'] = 'spelling_expansion_revert_click'
    paginationParams['cursor'] = None
    paginationParams['pc'] = '1'
    paginationParams['spelling_corrections'] = '1'
    paginationParams['ext'] = 'mediaStats,highlightedLabel'
  params <class 'dict'> = params = <builtins.dict>
    params['include_profile_interstitial_type'] = '1'
    params['include_blocking'] = '1'
    params['include_blocked_by'] = '1'
    params['include_followed_by'] = '1'
    params['include_want_retweets'] = '1'
    params['include_mute_edge'] = '1'
    params['include_can_dm'] = '1'
    params['include_can_media_tag'] = '1'
    params['skip_status'] = '1'
    params['cards_platform'] = 'Web-12'
    params['include_cards'] = '1'
    params['include_ext_alt_text'] = 'true'
    params['include_quote_count'] = 'true'
    params['include_reply_count'] = '1'
    params['tweet_mode'] = 'extended'
    params['include_entities'] = 'true'
    params['include_user_entities'] = 'true'
    params['include_ext_media_color'] = 'true'
    params['include_ext_media_availability'] = 'true'
    params['send_error_codes'] = 'true'
    params['simple_quoted_tweets'] = 'true'
    params['q'] = 'from:elonmusk'
    params['tweet_search_mode'] = 'live'
    params['count'] = '100'
    params['query_source'] = 'spelling_expansion_revert_click'
    params['pc'] = '1'
    params['spelling_corrections'] = '1'
    params['ext'] = 'mediaStats,highlightedLabel'

Object dict:
{'_retries': 3, '_session': <requests.sessions.Session object at 0x7f77177756a0>, '_baseUrl': 'https://twitter.com/elonmusk', '_guestTokenManager': <snscrape.modules.twitter._CLIGuestTokenManager object at 0x7f77177759a0>, '_apiHeaders': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', 'Authorization': 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA', 'Referer': 'https://twitter.com/search?f=live&lang=en&q=from%3Aelonmusk&src=spelling_expansion_revert_click', 'Accept-Language': 'en-US,en;q=0.5'}, '_userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', '_query': 'from:elonmusk', '_cursor': None, '_top': False, '_username': 'elonmusk', '_isUserId': False}

Locals from file "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data:
  self <class 'snscrape.modules.twitter.TwitterUserScraper'> = self = <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>
  endpoint <class 'str'> = endpoint = 'https://api.twitter.com/2/search/adaptive.json'
  params <class 'dict'> = params = <builtins.dict>
    params['include_profile_interstitial_type'] = '1'
    params['include_blocking'] = '1'
    params['include_blocked_by'] = '1'
    params['include_followed_by'] = '1'
    params['include_want_retweets'] = '1'
    params['include_mute_edge'] = '1'
    params['include_can_dm'] = '1'
    params['include_can_media_tag'] = '1'
    params['skip_status'] = '1'
    params['cards_platform'] = 'Web-12'
    params['include_cards'] = '1'
    params['include_ext_alt_text'] = 'true'
    params['include_quote_count'] = 'true'
    params['include_reply_count'] = '1'
    params['tweet_mode'] = 'extended'
    params['include_entities'] = 'true'
    params['include_user_entities'] = 'true'
    params['include_ext_media_color'] = 'true'
    params['include_ext_media_availability'] = 'true'
    params['send_error_codes'] = 'true'
    params['simple_quoted_tweets'] = 'true'
    params['q'] = 'from:elonmusk'
    params['tweet_search_mode'] = 'live'
    params['count'] = '100'
    params['query_source'] = 'spelling_expansion_revert_click'
    params['pc'] = '1'
    params['spelling_corrections'] = '1'
    params['ext'] = 'mediaStats,highlightedLabel'
  paginationParams <class 'dict'> = paginationParams = <builtins.dict>
    paginationParams['include_profile_interstitial_type'] = '1'
    paginationParams['include_blocking'] = '1'
    paginationParams['include_blocked_by'] = '1'
    paginationParams['include_followed_by'] = '1'
    paginationParams['include_want_retweets'] = '1'
    paginationParams['include_mute_edge'] = '1'
    paginationParams['include_can_dm'] = '1'
    paginationParams['include_can_media_tag'] = '1'
    paginationParams['skip_status'] = '1'
    paginationParams['cards_platform'] = 'Web-12'
    paginationParams['include_cards'] = '1'
    paginationParams['include_ext_alt_text'] = 'true'
    paginationParams['include_quote_count'] = 'true'
    paginationParams['include_reply_count'] = '1'
    paginationParams['tweet_mode'] = 'extended'
    paginationParams['include_entities'] = 'true'
    paginationParams['include_user_entities'] = 'true'
    paginationParams['include_ext_media_color'] = 'true'
    paginationParams['include_ext_media_availability'] = 'true'
    paginationParams['send_error_codes'] = 'true'
    paginationParams['simple_quoted_tweets'] = 'true'
    paginationParams['q'] = 'from:elonmusk'
    paginationParams['tweet_search_mode'] = 'live'
    paginationParams['count'] = '100'
    paginationParams['query_source'] = 'spelling_expansion_revert_click'
    paginationParams['cursor'] = None
    paginationParams['pc'] = '1'
    paginationParams['spelling_corrections'] = '1'
    paginationParams['ext'] = 'mediaStats,highlightedLabel'
  cursor <class 'NoneType'> = cursor = None
  direction <enum '_ScrollDirection'> = direction = <_ScrollDirection.BOTTOM: 2>
  reqParams <class 'dict'> = reqParams = <builtins.dict>
    reqParams['include_profile_interstitial_type'] = '1'
    reqParams['include_blocking'] = '1'
    reqParams['include_blocked_by'] = '1'
    reqParams['include_followed_by'] = '1'
    reqParams['include_want_retweets'] = '1'
    reqParams['include_mute_edge'] = '1'
    reqParams['include_can_dm'] = '1'
    reqParams['include_can_media_tag'] = '1'
    reqParams['skip_status'] = '1'
    reqParams['cards_platform'] = 'Web-12'
    reqParams['include_cards'] = '1'
    reqParams['include_ext_alt_text'] = 'true'
    reqParams['include_quote_count'] = 'true'
    reqParams['include_reply_count'] = '1'
    reqParams['tweet_mode'] = 'extended'
    reqParams['include_entities'] = 'true'
    reqParams['include_user_entities'] = 'true'
    reqParams['include_ext_media_color'] = 'true'
    reqParams['include_ext_media_availability'] = 'true'
    reqParams['send_error_codes'] = 'true'
    reqParams['simple_quoted_tweets'] = 'true'
    reqParams['q'] = 'from:elonmusk'
    reqParams['tweet_search_mode'] = 'live'
    reqParams['count'] = '100'
    reqParams['query_source'] = 'spelling_expansion_revert_click'
    reqParams['pc'] = '1'
    reqParams['spelling_corrections'] = '1'
    reqParams['ext'] = 'mediaStats,highlightedLabel'
  bottomCursorAndStop <class 'NoneType'> = bottomCursorAndStop = None
  dir <class 'str'> = dir = 'bottom'
  stopOnEmptyResponse <class 'bool'> = stopOnEmptyResponse = False
  emptyResponsesOnCursor <class 'int'> = emptyResponsesOnCursor = 0

Object dict:
{'_retries': 3, '_session': <requests.sessions.Session object at 0x7f77177756a0>, '_baseUrl': 'https://twitter.com/elonmusk', '_guestTokenManager': <snscrape.modules.twitter._CLIGuestTokenManager object at 0x7f77177759a0>, '_apiHeaders': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', 'Authorization': 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA', 'Referer': 'https://twitter.com/search?f=live&lang=en&q=from%3Aelonmusk&src=spelling_expansion_revert_click', 'Accept-Language': 'en-US,en;q=0.5'}, '_userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', '_query': 'from:elonmusk', '_cursor': None, '_top': False, '_username': 'elonmusk', '_isUserId': False}

Locals from file "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 338, in _get_api_data:
  self <class 'snscrape.modules.twitter.TwitterUserScraper'> = self = <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>
  endpoint <class 'str'> = endpoint = 'https://api.twitter.com/2/search/adaptive.json'
  params <class 'dict'> = params = <builtins.dict>
    params['include_profile_interstitial_type'] = '1'
    params['include_blocking'] = '1'
    params['include_blocked_by'] = '1'
    params['include_followed_by'] = '1'
    params['include_want_retweets'] = '1'
    params['include_mute_edge'] = '1'
    params['include_can_dm'] = '1'
    params['include_can_media_tag'] = '1'
    params['skip_status'] = '1'
    params['cards_platform'] = 'Web-12'
    params['include_cards'] = '1'
    params['include_ext_alt_text'] = 'true'
    params['include_quote_count'] = 'true'
    params['include_reply_count'] = '1'
    params['tweet_mode'] = 'extended'
    params['include_entities'] = 'true'
    params['include_user_entities'] = 'true'
    params['include_ext_media_color'] = 'true'
    params['include_ext_media_availability'] = 'true'
    params['send_error_codes'] = 'true'
    params['simple_quoted_tweets'] = 'true'
    params['q'] = 'from:elonmusk'
    params['tweet_search_mode'] = 'live'
    params['count'] = '100'
    params['query_source'] = 'spelling_expansion_revert_click'
    params['pc'] = '1'
    params['spelling_corrections'] = '1'
    params['ext'] = 'mediaStats,highlightedLabel'

Object dict:
{'_retries': 3, '_session': <requests.sessions.Session object at 0x7f77177756a0>, '_baseUrl': 'https://twitter.com/elonmusk', '_guestTokenManager': <snscrape.modules.twitter._CLIGuestTokenManager object at 0x7f77177759a0>, '_apiHeaders': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', 'Authorization': 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA', 'Referer': 'https://twitter.com/search?f=live&lang=en&q=from%3Aelonmusk&src=spelling_expansion_revert_click', 'Accept-Language': 'en-US,en;q=0.5'}, '_userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', '_query': 'from:elonmusk', '_cursor': None, '_top': False, '_username': 'elonmusk', '_isUserId': False}

Locals from file "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 301, in _ensure_guest_token:
  self <class 'snscrape.modules.twitter.TwitterUserScraper'> = self = <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>
  url <class 'NoneType'> = url = None

Object dict:
{'_retries': 3, '_session': <requests.sessions.Session object at 0x7f77177756a0>, '_baseUrl': 'https://twitter.com/elonmusk', '_guestTokenManager': <snscrape.modules.twitter._CLIGuestTokenManager object at 0x7f77177759a0>, '_apiHeaders': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', 'Authorization': 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA', 'Referer': 'https://twitter.com/search?f=live&lang=en&q=from%3Aelonmusk&src=spelling_expansion_revert_click', 'Accept-Language': 'en-US,en;q=0.5'}, '_userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', '_query': 'from:elonmusk', '_cursor': None, '_top': False, '_username': 'elonmusk', '_isUserId': False}

Locals from file "/usr/local/lib/python3.9/dist-packages/snscrape/base.py", line 216, in _get:
  self <class 'snscrape.modules.twitter.TwitterUserScraper'> = self = <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>
  args <class 'tuple'> = args = ('https://twitter.com/elonmusk',)
  kwargs <class 'dict'> = kwargs = <builtins.dict>
    kwargs['headers'] = <builtins.dict>
      kwargs['headers']['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58'       
    kwargs['responseOkCallback'] = <bound method _TwitterAPIScraper._check_guest_token_response of <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>>

Object dict:
{'_retries': 3, '_session': <requests.sessions.Session object at 0x7f77177756a0>, '_baseUrl': 'https://twitter.com/elonmusk', '_guestTokenManager': <snscrape.modules.twitter._CLIGuestTokenManager object at 0x7f77177759a0>, '_apiHeaders': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', 'Authorization': 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA', 'Referer': 'https://twitter.com/search?f=live&lang=en&q=from%3Aelonmusk&src=spelling_expansion_revert_click', 'Accept-Language': 'en-US,en;q=0.5'}, '_userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', '_query': 'from:elonmusk', '_cursor': None, '_top': False, '_username': 'elonmusk', '_isUserId': False}

Locals from file "/usr/local/lib/python3.9/dist-packages/snscrape/base.py", line 212, in _request:
  self <class 'snscrape.modules.twitter.TwitterUserScraper'> = self = <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>
  method <class 'str'> = method = 'GET'
  url <class 'str'> = url = 'https://twitter.com/elonmusk'
  params <class 'NoneType'> = params = None
  data <class 'NoneType'> = data = None
  headers <class 'dict'> = headers = <builtins.dict>
    headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58'
  timeout <class 'int'> = timeout = 10
  responseOkCallback <class 'method'> = responseOkCallback = <bound method _TwitterAPIScraper._check_guest_token_response of <snscrape.modules.twitter.TwitterUserScraper object at 0x7f7717775760>>
  allowRedirects <class 'bool'> = allowRedirects = True
  attempt <class 'int'> = attempt = 3
  req <class 'requests.models.PreparedRequest'> = req = <PreparedRequest [GET]>
    req.method = GET
    req.url = https://twitter.com/elonmusk
    req.headers = \
      User-Agent = _ = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58'
      Accept-Encoding = _ = 'gzip, deflate'
      Accept = _ = '*/*'
      Connection = _ = 'keep-alive'
  retrying <class 'str'> = retrying = ''
  level <class 'int'> = level = 40
  msg <class 'str'> = msg = '4 requests to https://twitter.com/elonmusk failed, giving up.'
  sleepTime <class 'float'> = sleepTime = 4.0

Object dict:
{'_retries': 3, '_session': <requests.sessions.Session object at 0x7f77177756a0>, '_baseUrl': 'https://twitter.com/elonmusk', '_guestTokenManager': <snscrape.modules.twitter._CLIGuestTokenManager object at 0x7f77177759a0>, '_apiHeaders': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', 'Authorization': 'Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs=1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA', 'Referer': 'https://twitter.com/search?f=live&lang=en&q=from%3Aelonmusk&src=spelling_expansion_revert_click', 'Accept-Language': 'en-US,en;q=0.5'}, '_userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.5175 Safari/537.58', '_query': 'from:elonmusk', '_cursor': None, '_top': False, '_username': 'elonmusk', '_isUserId': False
```

This was performed on a virtual machine, but access to Twitter is free and clear.

**Comment by JustAnotherArchivist** [comment]
What are the log messages? There should be something like `Error retrieving https://twitter.com/elonmusk: ...` at the `FATAL` level just before the exception gets raised.

**Comment by T145** [comment]
That was the entire temporary log that was generated. The log message after running the command is:
```
2022-08-25 13:08:05.386  ERROR  snscrape.base  Error retrieving https://twitter.com/elonmusk: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='twitter.com', 
port=443): Max retries exceeded with url: /elonmusk (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fecb750f4c0>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
2022-08-25 13:08:05.386  CRITICAL  snscrape.base  4 requests to https://twitter.com/elonmusk failed, giving up.
2022-08-25 13:08:05.435  CRITICAL  snscrape._cli  Dumped stack and locals to /tmp/snscrape_locals_x6psp0pq
Traceback (most recent call last):
  File "/usr/local/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 753, in get_items
    yield from super().get_items()
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 338, in _get_api_data
    self._ensure_guest_token()
  File "/usr/local/lib/python3.9/dist-packages/snscrape/modules/twitter.py", line 301, in _ensure_guest_token
    r = self._get(self._baseUrl if url is None else url, headers = {'User-Agent': self._userAgent}, responseOkCallback = self._check_guest_token_response)
  File "/usr/local/lib/python3.9/dist-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://twitter.com/elonmusk failed, giving up.
```

**Comment by JustAnotherArchivist** [comment]
`Connection refused`? I've never seen that myself, not even on bans; however, someone has reported getting it on AWS-based machines before (#217). Assuming it's not that, are you sure there isn't something interfering in the network, like a firewall or proxy? It works fine here from three continents.

**Comment by T145** [comment]
That was the first thing I tried to remedy. While there is a fair amount of proxying, local firewalls, and remote firewalls incorporated throughout used devices, these were all disabled to the best of my ability. I tried running this program on a Docker container from a laptop connected to a cellphone hotspot. All hosts file changes were reset and all firewall protocols were disabled on the laptop. To my knowledge nothing would be actively filtering the cellular connection at the time either.

My Dockerfile is located here: https://github.com/T145/black-mirror/blob/master/Dockerfile
And the image can be run like so:
```bash
docker container run -it --rm -h black-mirror ghcr.io/t145/black-mirror
```

**Comment by TheTechRobo** [comment]
Are you sure Docker isn't interfering?

**Comment by T145** [comment]
> Are you sure Docker isn't interfering?

I don't see why it would be, considering I'm able to upload and download from the container well enough.
Of course pinging the website would return a localhost IP but CURL can interface with the Twitter API.

**Comment by T145** [comment]
> Are you sure Docker isn't interfering?

Testing under the same conditions as last time to double check the CURL calls yielded this:

```
┌─[root@2dd37e7f4363]─[/]
└──╼ #curl www.twitter.com
curl: (7) Failed to connect to www.twitter.com port 80 after 76 ms: Connection refused
┌─[✗]─[root@2dd37e7f4363]─[/]
└──╼ #curl twitter.com
curl: (7) Failed to connect to twitter.com port 80 after 45 ms: Connection refused
┌─[✗]─[root@2dd37e7f4363]─[/]
└──╼ #curl https://twitter.com
curl: (7) Failed to connect to twitter.com port 443 after 178 ms: Connection refused
```

**Comment by JustAnotherArchivist** [comment]
So it is an issue with your networking then. I'm afraid I have no clue what might cause this though.

**Comment by JustAnotherArchivist** [comment]
Feel free to still post here if you figure it out. Might be useful to others. :-)
