### ISSUE TITLE
Error -- snscrape.base.ScraperException

### ISSUE THREAD

**Issue by ehsong** [JustAnotherArchivist/snscrape#565]
I used snscrape before and it worked fine but yesterday I got a few error messages and the scraper stopped midway. Will scraping for shorter period of time mitigate the problem? I was trying to scrape a large amount of tweets, for a period of a year.
```
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%EC%9D%BC%EB%B3%B8since%3A2019-01-01+until%3A2020-01-01+-filter%3Alinks+-filter%3Areplies&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&cursor=scroll%3AthGAVUV0VFVBaAwKq9g6SKhyAWgMC16eqHu9IhEnEVt6yRAhWAiXoYB0RFRkFVTFQ1ARXIgAIVAAA%3D&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: blocked (403)
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%EC%9D%BC%EB%B3%B8since%3A2019-01-01+until%3A2020-01-01+-filter%3Alinks+-filter%3Areplies&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&cursor=scroll%3AthGAVUV0VFVBaAwKq9g6SKhyAWgMC16eqHu9IhEnEVt6yRAhWAiXoYB0RFRkFVTFQ1ARXIgAIVAAA%3D&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
Traceback (most recent call last):
  File "/Users/esthersong/Dropbox/COVID-Anti-China-Korea Copy/script and data/japan_script1.py", line 22, in <module>
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(keyword + 'since:' +  start + ' until:' +                                                         stop + ' -filter:links -filter:replies').get_items()):
  File "/Users/esthersong/opt/anaconda3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 595, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/Users/esthersong/opt/anaconda3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 289, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/Users/esthersong/opt/anaconda3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 259, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/Users/esthersong/opt/anaconda3/lib/python3.9/site-packages/snscrape/base.py", line 212, in _get
    return self._request('GET', *args, **kwargs)
  File "/Users/esthersong/opt/anaconda3/lib/python3.9/site-packages/snscrape/base.py", line 208, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%EC%9D%BC%EB%B3%B8since%3A2019-01-01+until%3A2020-01-01+-filter%3Alinks+-filter%3Areplies&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&cursor=scroll%3AthGAVUV0VFVBaAwKq9g6SKhyAWgMC16eqHu9IhEnEVt6yRAhWAiXoYB0RFRkFVTFQ1ARXIgAIVAAA%3D&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
```

**Comment by JustAnotherArchivist** [comment]
You're missing a space before the `since` filter. I'm not sure that's related though. The CLI would generate a dump file when it crashes, which may help shed more light on this.

**Comment by ajeetlabs** [comment]
hey @ehsong did you find the solution of it I am getting the same error.

**Comment by JustAnotherArchivist** [comment]
Not actionable without more information, scraping works fine for me and others from several locations.
