### ISSUE TITLE
Twitter-profile is not functioning

### ISSUE THREAD

**Issue by sh1dow3r** [JustAnotherArchivist/snscrape#582]
Thank you for this awesome tool.. 

I was playing with this for a couple of weeks now and today I encountered an issue on the twitter-profile functionality. 

I'm using python 3.10 and snscrape==0.4.3.20220106  (latest version)

## How to replicate the issue: 

Command:
`$ snscrape --jsonl --max-result 15 twitter-profile 'ElonMusk' `

Output: 
```
2022-11-06 12:43:41.298  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/timeline/profile/44196397.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&include_tweet_replies=true&userId=44196397&count=100&ext=mediaStats%2ChighlightedLabel: blocked (429)
2022-11-06 12:43:41.299  CRITICAL  snscrape.base  4 requests to https://api.twitter.com/2/timeline/profile/44196397.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&include_tweet_replies=true&userId=44196397&count=100&ext=mediaStats%2ChighlightedLabel failed, giving up.
2022-11-06 12:43:41.336  CRITICAL  snscrape._cli  Dumped stack and locals to /var/folders/d_/prpx8rb938ngjtw1__87r49w0000gn/T/snscrape_locals_96e8ni6_
Traceback (most recent call last):
  File "/private/tmp/hps/env/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/private/tmp/hps/env/lib/python3.10/site-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/private/tmp/hps/env/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 813, in get_items
    for obj in self._iter_api_data(f'https://api.twitter.com/2/timeline/profile/{userId}.json', params, paginationParams):
  File "/private/tmp/hps/env/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "/private/tmp/hps/env/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/private/tmp/hps/env/lib/python3.10/site-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "/private/tmp/hps/env/lib/python3.10/site-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/timeline/profile/44196397.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&include_tweet_replies=true&userId=44196397&count=100&ext=mediaStats%2ChighlightedLabel failed, giving up.
       0
```
       
It used to work for me until yesterday, tried different versions but still the same issue resides..

**Comment by JustAnotherArchivist** [comment]
> blocked (429)

Your IP is banned from Twitter (probably temporarily). Naturally, I can't tell you why. Maybe you ran too many scrapes at once or too frequently, or maybe Twitter just hates you/your IP. I haven't been able to trigger this myself so far, but in any case, there's nothing snscrape can do to get around it. You'll need to wait for the ban to expire or change your IP.

**Comment by JustAnotherArchivist** [comment]
Oh, I totally missed the version and didn't look at the URL. This isn't a ban. It's the old endpoint. You'll need the dev version for now.

#367

**Comment by sh1dow3r** [comment]
Thank you, works now..
