### ISSUE TITLE
Mastodon: Crash when attempting to retrieve data from Mastodon servers running v4.0.0

### ISSUE THREAD

**Issue by caseyho** [JustAnotherArchivist/snscrape#587]
Crash occurs when attempting to retrieve data from a user profile at mastodon.social (v4.0.0rc1) or mstdn.social (v4.0.0rc1) while using snscrape 0.4.3.20220107.dev64+g59abeaf 

Crash does not occur when retrieving data from servers running earlier versions of Mastodon (3.x.x)

Doing so yields the following stack trace:

```
Traceback (most recent call last):
  File "[path-to-lib]\site-packages\snscrape\_cli.py", line 116, in _dump_locals_on_exception
    yield
  File "[path-to-lib]\site-packages\snscrape\_cli.py", line 318, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "[path-to-lib]\site-packages\snscrape\modules\mastodon.py", line 279, in get_items
    yield from self._entries_to_items(soup.find('div', class_ = 'activity-stream').find_all('div', class_ = 'entry'), r.url)
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by Wamy-Dev** [comment]
Any status on this?
