### ISSUE TITLE
snscrape.base.ScraperException: Unable to connect to Twitter API

### ISSUE THREAD

**Issue by and-sanford** [JustAnotherArchivist/snscrape#635]
### Describe the bug

Hi there! 
I've been using snscrape's twitter module `sntwitter.TwitterSearchScraper` as part of [my Python program](https://github.com/and-sanford/third-party-twitter-account-archiver). 

Tonight, it stopped working. It was working around 6 hours ago. I've made no OS updates or other env changes. I've double-checked that I'm up to date on snscrape's package. I've also attempted running the script from different IPs, but I still get a "cannot connect" error message. And I've attempted with multiple user accounts - all return the same error message. It appears to me there's some sort of API authentication issue. Twitter says their APIs are up (though who knows if that's accurate), but I wanted to inform you.

I'm running on Python v3.11.0

### How to reproduce

You can repro in two ways (both return the same error message)

1. CLI
snscrape twitter-user {account}

2. Python
import snscrape.modules.twitter as sntwitter
for _tmp, tweet in enumerate(sntwitter.TwitterSearchScraper(f'''
                                    from:{account}
                                    include:nativeretweets
                                    ''').get_items()):
    print(tweet)

### Expected behavior

CLI or Python script should return a (generator) object that can be iterated against.

### OS / Distro

MacOS 12.5

### Output from `snscrape --version`

0.4.3.20220106

### Scraper

twitter-user, snscrape.modules.twitter

### Backtrace

snscrape twitter-user jack

2023-01-10 18:55:18.852  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3Ajack&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
2023-01-10 18:55:18.852  CRITICAL  snscrape.base  4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3Ajack&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
2023-01-10 18:55:18.875  CRITICAL  snscrape._cli  Dumped stack and locals to /var/folders/hm/q24ctcxd1d34bbw3ytvc487w0000gn/T/snscrape_locals_y21ih9ch
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/snscrape", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/snscrape/_cli.py", line 308, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 753, in get_items
    yield from super().get_items()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=from%3Ajack&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

### How are you using snscrape?

Module

**Comment by Nasseh123** [comment]
I am also experiencing this.

**Comment by jieklee** [comment]
Yes, I'm facing this issue also. Please help.
Python version 3.9.12

**Comment by Nasseh123** [comment]
I can see the issue is with an update from Twitter.
Follow this thread  #634

**Comment by and-sanford** [comment]
Thanks! I thought that was a different issue. I’ll try that!

**Comment by and-sanford** [comment]
Also, thanks so much for making this - is been an incredible tool ❤️
