### ISSUE TITLE
"Unable to find guest token" on all twitter-user calls

### ISSUE THREAD

**Issue by jodizzle** [JustAnotherArchivist/snscrape#64]
With `snscrape twitter-user twitter`:
```
2020-06-23 22:02:25.001  CRITICAL  snscrape.cli  Dumped stack and locals to /tmp/snscrape_locals_yfgq2yve
Traceback (most recent call last):
  File "/home/user/snscrape/env/bin/snscrape", line 11, in <module>
    load_entry_point('snscrape', 'console_scripts', 'snscrape')()
  File "/home/user/snscrape/snscrape/cli.py", line 230, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/home/user/snscrape/snscrape/modules/twitter.py", line 126, in get_items
    guestToken = self._get_guest_token()
  File "/home/user/snscrape/snscrape/modules/twitter.py", line 103, in _get_guest_token
    raise snscrape.base.ScraperException('Unable to find guest token')
snscrape.base.ScraperException: Unable to find guest token
```
This seems like it's the case for every account.

**Comment by JustAnotherArchivist** [comment]
Yep, Twitter changed the way tokens are handed out. Testing a fix now.
