### ISSUE TITLE
snscrape error windows 10

### ISSUE THREAD

**Issue by AlesyaSeliazniova30032012** [JustAnotherArchivist/snscrape#644]
2023-01-11 14:55:49 DESKTOP-3F7BL1O snscrape.modules.twitter[9164] INFO Retrieving scroll page None
2023-01-11 14:55:49 DESKTOP-3F7BL1O snscrape.modules.twitter[9164] INFO Retrieving guest token
2023-01-11 14:55:49 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieving https://twitter.com/search?f=live&lang=en&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&src=spelling_expansion_revert_click
2023-01-11 14:55:50 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieved https://twitter.com/search?f=live&lang=en&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&src=spelling_expansion_revert_click: 200
2023-01-11 14:55:50 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel
2023-01-11 14:55:51 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieved https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: 401
2023-01-11 14:55:51 DESKTOP-3F7BL1O snscrape.base[9164] INFO Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code, retrying
2023-01-11 14:55:51 DESKTOP-3F7BL1O snscrape.base[9164] INFO Waiting 1 seconds
2023-01-11 14:55:52 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel
2023-01-11 14:55:52 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieved https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: 401
2023-01-11 14:55:52 DESKTOP-3F7BL1O snscrape.base[9164] INFO Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code, retrying
2023-01-11 14:55:52 DESKTOP-3F7BL1O snscrape.base[9164] INFO Waiting 2 seconds
2023-01-11 14:55:54 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel
2023-01-11 14:55:54 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieved https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: 401
2023-01-11 14:55:54 DESKTOP-3F7BL1O snscrape.base[9164] INFO Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code, retrying
2023-01-11 14:55:54 DESKTOP-3F7BL1O snscrape.base[9164] INFO Waiting 4 seconds
2023-01-11 14:55:58 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel
2023-01-11 14:55:58 DESKTOP-3F7BL1O snscrape.base[9164] INFO Retrieved https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: 401
2023-01-11 14:55:58 DESKTOP-3F7BL1O snscrape.base[9164] ERROR Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
2023-01-11 14:55:58 DESKTOP-3F7BL1O snscrape.base[9164] CRITICAL 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
Traceback (most recent call last):
  File "C:\Users\m68000\PycharmProjects\Thestag\thestag\snscrape_10_tabloids.py", line 74, in <module>
    cl.get_tweets()
  File "C:\Users\m68000\PycharmProjects\Thestag\thestag\snscrape_10_tabloids.py", line 52, in get_tweets
    for tweet in sntwitter.TwitterSearchScraper(query).get_items():
  File "C:\Users\m68000\TheStag\lib\site-packages\snscrape\modules\twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "C:\Users\m68000\TheStag\lib\site-packages\snscrape\modules\twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "C:\Users\m68000\TheStag\lib\site-packages\snscrape\modules\twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "C:\Users\m68000\TheStag\lib\site-packages\snscrape\base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "C:\Users\m68000\TheStag\lib\site-packages\snscrape\base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=%28from%3AAJEnglish+OR+from%3AAJENews+OR+from%3ACNN+OR+from%3Acnnbrk+OR+from%3Acnni+OR+from%3ACNNPolitics+OR+from%3AMailOnline+OR+from%3ADailyMail+OR+from%3ASkyNews+OR+from%3ASkyNewsBreak+OR+from%3Aafricanews+OR+from%3ABBCAfrica+OR+from%3Anytimes+OR+from%3Anytimesworld+OR+from%3AFoxNews+OR+from%3Afoxnewspolitics+OR+from%3ABBCBreaking+OR+from%3ABBCWorld+OR+from%3ABBCNews+OR+from%3ABBCPolitics+OR+from%3AMSN+OR+from%3Amsnindia%29+until%3A2023-01-12+since%3A2023-01-11+%28filter%3Asafe+OR+-filter%3Asafe%29&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.

this problem appeared today. before that, scraping came without failures. I looked at similar solutions, added a filter (filter:safe OR -filter:safe). nothing has changed. tell me what the problem is. on twitter?
`import snscrape.modules.twitter as sntwitter
import datetime as dt
from resolution_helper import get_market_resolution

list_for_query = ['AJEnglish', 'AJENews', 'CNN', 'cnnbrk', 'cnni', 'CNNPolitics', 'MailOnline', 'DailyMail',
                  'SkyNews', 'SkyNewsBreak', 'africanews', 'BBCAfrica', 'nytimes', 'nytimesworld', 'FoxNews',
                  'foxnewspolitics', 'BBCBreaking', 'BBCWorld', 'BBCNews', 'BBCPolitics', 'MSN', 'msnindia']
tomorrow = (dt.datetime.today().date() + dt.timedelta(days=1)).strftime('%Y-%m-%d')
today = (dt.datetime.today().date()).strftime('%Y-%m-%d')
dates = {'tomorrow': tomorrow, 'today': today}
list_for_query += [dates[key] for key in dates]
queries = []

def query_set(replies=False, tweets_query=None, reply_query=None):
    queries.append(tweets_query)
    if replies:
        queries.append(reply_query)
        return queries

class TweetData:
    def __init__(self, time_parse):
        self.time_parse = time_parse
        self.time_delay = get_market_resolution(resolution_string=self.time_parse)
        self.tweets = set()
        self.tweet_query = ('(from:{}' + ' OR from:{}' * 21 + ') until:{} since:{} (filter:safe OR -filter:safe)').format(*list_for_query)
        self.reply_query = ('(to:{}' + ' OR to:{}' * 21 + ') filter:replies until:{} since:{} (filter:safe OR -filter:safe)').format(*list_for_query)

    def get_tweets(self):
        tw_queries = query_set(replies=True, tweets_query=self.tweet_query, reply_query=self.reply_query)
        for query in tw_queries:
            for tweet in sntwitter.TwitterSearchScraper(query).get_items():
                if tweet.date < (dt.datetime.now(dt.timezone.utc) - dt.timedelta(seconds=self.time_delay)) or \
                        tweet.content in self.tweets:
                    continue
                tweet.content = tweet.content.replace("\n", " ")
                self.tweets.add(tweet.content)
        print(list(self.tweets))
        return list(self.tweets)

cl = TweetData(time_parse='10_min')
cl.get_tweets()`

**Comment by Mr-Freewan** [comment]
Why don't you read the other questions? Just today this topic has been discussed several times

**Comment by cypher437** [comment]
Same, just got this happening recently. Before today no problem.

`raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=since%3A2023-01-11T11%3A17%3A38+from%3Aadam3us&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.`

**Comment by AlesyaSeliazniova30032012** [comment]
> Why don't you read the other questions? Just today this topic has been discussed several times

you can tell me where I can read similar questions and throw off links, I do not know, the first time is here. thanks

**Comment by JustAnotherArchivist** [comment]
#634
