### ISSUE TITLE
Twitter API Call Failing

### ISSUE THREAD

**Issue by nv78** [JustAnotherArchivist/snscrape#650]
### Describe the bug

This code worked yesterday, but is now failing. How do I fix this?
```python
import snscrape.modules.twitter as sntwitter
import pandas as pd
from datetime import date

def get_tweets_from_user(
    user: str = 'john',
    n_tweets: int = 150
) -> pd.DataFrame:
    # To Run: get_tweets_from_user('john', n_tweets=15)

    query = "from:" + str(user)
    # Created a list to append all tweet attributes(data)
    attributes_container = []

    # Using TwitterSearchScraper to scrape data and append tweets to list
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query).get_items()):
        if i>n_tweets:
            break
        attributes_container.append([tweet.date, tweet.likeCount, tweet.sourceLabel, tweet.content])

    # Creating a dataframe from the tweets list above
    tweets_df = pd.DataFrame(attributes_container, columns=["Date Created", "Number of Likes", "Source of Tweet", "Text"])

    return tweets_df

def search_tweets(
    search_query: str,
    n_tweets: int = 150,
    start_date: str = "2022-06-06",
    end_date: str = "2022-07-06",
) -> pd.DataFrame:
    # To Run: search_tweets('arsenal soccer', '2022-06-06' ,'2022-07-06', n_tweets=15)

    query = str(search_query) + " since:" + str(start_date) + " until:" + str(end_date)
    # Creating list to append tweet data to
    attributes_container = []

    # Using TwitterSearchScraper to scrape data and append tweets to list
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query, top=False).get_items()):
        if i>n_tweets:
            break
        attributes_container.append([tweet.user.username, tweet.date, tweet.likeCount, tweet.sourceLabel, tweet.content])

    # Creating a dataframe to load the list
    tweets_df = pd.DataFrame(attributes_container, columns=["User", "Date Created", "Number of Likes", "Source of Tweet", "Text"])

    return tweets_df

get_tweets_from_user("elonmusk")

search_tweets("New York City")
```
### How to reproduce

Run the code above

### Expected behavior

We expect to get the top tweets from a user or search query.

### OS / Distro

MacOS

### Output from `snscrape --version`

Error

### Scraper

twitter-user, twitter-search

### Backtrace

```
python -u "/Users/natanvidra/Workspace/Anote-Prototype/server/connectors/twitter.py"
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=New+York+City+since%3A2022-06-06+until%3A2022-07-06&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo: non-200 status code
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=New+York+City+since%3A2022-06-06+until%3A2022-07-06&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.
Traceback (most recent call last):
  File "/Users/natanvidra/Workspace/Anote-Prototype/server/connectors/twitter.py", line 55, in <module>
    search_tweets("New York City")
  File "/Users/natanvidra/Workspace/Anote-Prototype/server/connectors/twitter.py", line 43, in search_tweets
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query, top=False).get_items()):
  File "/Users/natanvidra/miniforge3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 1453, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "/Users/natanvidra/miniforge3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 720, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
  File "/Users/natanvidra/miniforge3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 690, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/Users/natanvidra/miniforge3/lib/python3.9/site-packages/snscrape/base.py", line 221, in _get
    return self._request('GET', *args, **kwargs)
  File "/Users/natanvidra/miniforge3/lib/python3.9/site-packages/snscrape/base.py", line 217, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=New+York+City+since%3A2022-06-06+until%3A2022-07-06&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo failed, giving up.
```

### How are you using snscrape?

CLI

**Comment by JustAnotherArchivist** [comment]
#634

**Comment by nv78** [comment]
Looked at #634, is there a way to fix this?
