### ISSUE TITLE
Twitter scraping: raise ScraperException(msg) snscrape.base.ScraperException: 4 requests to ......

### ISSUE THREAD

**Issue by lukaszpeee** [JustAnotherArchivist/snscrape#668]
I got an issue as in the title. What does it mean? The code worked few days ago. Is possible to fix that? Simple code below:

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd

tweets_list1 = []

for i, tweet in enumerate(sntwitter.TwitterSearchScraper('from:jack').get_items()):
    if i > 100:
        break
    tweets_list1.append([tweet.date, tweet.content])

tweets_df1 = pd.DataFrame(tweets_list1, columns=['Datetime', 'Text'])
print(tweets_df1)
```

Full error:

```
Error retrieving (long link): non-200 status code
4 requests to (long link)failed, giving up.
Traceback (most recent call last):
  File "C:\Users\rogal\Desktop\Python\KOD\PROJEKTY\cryptotweetapp\checker_file.py", line 8, in <module>
    for i, tweet in enumerate(sntwitter.TwitterSearchScraper('from:jack').get_items()):
  File "C:\Users\rogal\Desktop\Python\KOD\PROJEKTY\cryptotweetapp\env\lib\site-packages\snscrape\modules\twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "C:\Users\rogal\Desktop\Python\KOD\PROJEKTY\cryptotweetapp\env\lib\site-packages\snscrape\modules\twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
  File "C:\Users\rogal\Desktop\Python\KOD\PROJEKTY\cryptotweetapp\env\lib\site-packages\snscrape\modules\twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "C:\Users\rogal\Desktop\Python\KOD\PROJEKTY\cryptotweetapp\env\lib\site-packages\snscrape\base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
  File "C:\Users\rogal\Desktop\Python\KOD\PROJEKTY\cryptotweetapp\env\lib\site-packages\snscrape\base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to (long link) failed, giving up.
```

**Comment by ilkeronurisik** [comment]
Please read. #634
