### ISSUE TITLE
Anyone has encountered the error as shown below?

### ISSUE THREAD

**Issue by somaria** [JustAnotherArchivist/snscrape#670]
admin@mac snscrape % snscrape --jsonl twitter-tweet 1541874762997239808 > tweet.json
2023-01-14 00:11:27.100  CRITICAL  snscrape._cli  Dumped stack and locals to /var/folders/00/p4jjvymx4x3b5m003h8vp0vr0000gp/T/snscrape_locals_wr_94_e7
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/snscrape", line 11, in <module>
    load_entry_point('snscrape==0.4.3.20220107.dev56+gd72b519', 'console_scripts', 'snscrape')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/_cli.py", line 318, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/modules/twitter.py", line 1661, in get_items
    yield self._graphql_timeline_tweet_item_result_to_tweet(entry['content']['itemContent']['tweet_results']['result'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/modules/twitter.py", line 1300, in _graphql_timeline_tweet_item_result_to_tweet
    return self._make_tweet(tweet, user, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/snscrape-0.4.3.20220107.dev56+gd72b519-py3.8.egg/snscrape/modules/twitter.py", line 854, in _make_tweet
    kwargs['source'] = tweet['source']
KeyError: 'source'

**Comment by JustAnotherArchivist** [comment]
Yes, Twitter removed the source label this morning. It's already fixed on the current dev version.

**Comment by JustAnotherArchivist** [comment]
Relevant commit: 27374285
