### ISSUE TITLE
TwitterSearchScraper still not working with top=True on python V3.8.16 and openssl V3.0.7

### ISSUE THREAD

**Issue by FLXNO** [JustAnotherArchivist/snscrape#673]
### Describe the bug

As everyone else I ran into trouble with my twitter scraping application.
It was suggested, to set the "top" argument of TwitterSearchScraper to True in order to fix the issue and this should work for python 3.8.16 and openssl version 3.0.7.

I uninstalled snscrape and re-installed it to get the latest version via:
`pip3.8 install git+https://github.com/JustAnotherArchivist/snscrape`
Is this the right way to obtain the latest development version? (Sorry in advance, Im a little new to all of this)

`pip3.8 list`
returns
`snscrape               0.4.3.20220107.dev93+g1fb5c39`

So I did just that. Installed python 3.8.16 and openssl version 3.0.7, set top = True and it still fails.
I use a raspberry pi. Could that be the issue?

`python3.8 -V`
`Python 3.8.16`

`openssl version`
`OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)`

```python3
for i,tweet in enumerate(sntwitter.TwitterSearchScraper("from:maischberger", top = True).get_items()):
    # do stuff
```

Error message:
```
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Amaischberger&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: non-200 status code (404)
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Amaischberger&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
Errors: non-200 status code (404), non-200 status code (404), non-200 status code (404), non-200 status code (404)
Traceback (most recent call last):
  File "twitter.py", line 720, in <module>
    Scraper = TwitterScraper()
  File "twitter.py", line 66, in __init__
    self.get_tweets_talkshow(username = "maischberger")
  File "twitter.py", line 273, in get_tweets_talkshow
    for i,tweet in enumerate(sntwitter.TwitterSearchScraper(query, top=True).get_items()):
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 1546, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 759, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/modules/twitter.py", line 725, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/base.py", line 225, in _get
    return self._request('GET', *args, **kwargs)
  File "/home/pi/.local/lib/python3.8/site-packages/snscrape/base.py", line 221, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Amaischberger&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
```

Am I still missing something?

### How to reproduce

I can reproduce the issue by trying the same code for different python versions and my old openssl version.

### Expected behavior

The loop should return the tweets of the given user.

### OS / Distro

Raspbian

### Output from `snscrape --version`

snscrape               0.4.3.20220107.dev93+g1fb5c39

### Scraper

TwitterSearchScraper

### How are you using snscrape?

Module

**Comment by SomKen** [comment]
Weird... I'm able to get tweets from that user without issues. Does `from:maischberger since:2023-01-10 until:2023-01-12` work?

**Comment by JustAnotherArchivist** [comment]
Can you try with the new release? It shouldn't make a difference though as the only difference to the commit in your version number is a metadata format change, but yeah, you're not on the latest version currently.

Maybe OpenSSL supports different ciphers on a Raspberry Pi than a normal x64 computer? What does `openssl ciphers` say?

I might need to add debugging output for the cipher that actually gets selected.

**Comment by FLXNO** [comment]
Sorry guys. I just rebootet the pi and now it works like a charm. No idea what was the particular issue there.
Thanks @JustAnotherArchivist for all the work you put into the framework especially in the last days!!!!!!

**Comment by JustAnotherArchivist** [comment]
Good to hear.

I'll take this opportunity to note that logging the active cipher in a non-hacky way (i.e. no private APIs or monkeypatching) appears to be impossible. `requests` does not publicly expose the `urllib3.PoolManager`, only a method to create it (which sets an undocumented attribute rather than returning the object), and the `PoolManager` doesn't expose the `urllib3.HTTPSConnectionPool` either. Both would be needed to get to the underlying `http.client.HTTPSConnection`, which has the socket with the cipher information.
