### ISSUE TITLE
VK scraper crashes with 'ScraperException: Got an unknown response: '"\\/blank.php?...' on some profiles

### ISSUE THREAD

**Issue by JustAnotherArchivist** [JustAnotherArchivist/snscrape#68]
Scraping https://vk.com/degradination crashes with:

```
Traceback (most recent call last):
  File ".../bin/snscrape", line 11, in <module>
    load_entry_point('snscrape', 'console_scripts', 'snscrape')()
  File ".../snscrape/cli.py", line 261, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File ".../snscrape/modules/vkontakte.py", line 120, in get_items
    raise snscrape.base.ScraperException(f'Got an unknown response: {posts[:200]!r}...')
snscrape.base.ScraperException: Got an unknown response: '"\\/blank.php?block=119910902"'...
```

This happens on pagination with parameters `act=get_wall&al=1&fixed=4055663&offset=11340&onlyCache=false&owner_id=-39439883&type=own&wall_start_from=11340`.

The response content is very odd:

```python
r.content = b'{"payload":["4",["\\"\\\\\\/blank.php?block=119910902\\"","0"]],"static":"ui_common.css,cmodules\\/bundles\\/vendors.a1beb22ad8f0da2c28d6.js,cmodules\\/bundles\\/common.e3a62fd092c2c20cd73e.js,cmodules\\/bundles\\/4060411aa2c063eade7896c7daf24353.86af82472f24a738380b.js,cmodules\\/bundles\\/7d63c2e721572c4d155a33cbc032b85d.76c4da70e5bdaf4ef591.js,cmodules\\/web\\/ui_common.3c2297041db1a49913be.js","statsMeta":{"platform":"web2","st":false,"time":1599771914,"hash":"D7eMNkFupflnGmyqr6zHuRCZZaYzQX6lxUkzKHYDDKs"},"loaderVersion":"6282712","langPack":3,"langVersion":"4389","langKeys":{"global":[],"local":{"audio_delete_audio":"Delete track","audio_dont_show":"Stop suggesting","audio_performers_only":"by artist","audio_open_album":"Open album","audio_titles_search":"by title","audio_global_search_found":["","%s audio file found","%s audio files found"],"audio_site_rules_violation_warning":"{audio} has been removed from public access for violating the VK Terms of Service.","audio_site_rules_violation_header":"Prohibited audio file","audio_claim_delete":"delete the audio file","audio_claim_delete_capital":"Delete track","audio_claim_objection":"by filling out a special form","audio_claim_warning":"The audio file {audio} was removed from public access by request of the copyright holder.","audio_claim_warning_title":"Arguable Audio File","audio_claimed_geo":"{audio} is not available in your region.","audio_claimed_replacement_available":"This audio file has been blocked at the request of the copyright holder. You can replace it with the original audio file of the copyright holder <b>{original}<\\/b>.","audio_replace_with_original":"Replace","box_close":"Close","captcha_cancel":"Cancel","captcha_enter_code":"Enter the code from the picture","captcha_send":"Send","friends_no_user_selected":"You haven&#39;t selected anyone.","global_action_confirmation":"Confirm action","global_apps":"Apps","global_audio_ad":"Ads","global_audio_only_with_subscription_btn":"Learn more","global_audio_only_with_subscription_text":"Access has been limited by the artist or their representative. Subscribe and gain access to a wider range of music.","global_audio_only_with_subscription_title":"This track is only available through subscription","global_back":"Back","global_box_error_title":"Error","global_box_title_back":"Back","global_cancel":"Cancel","global_captcha_input_here":"Enter code","global_chats":"Chats","global_close":"Close","global_communities":"Communities","global_date":["","{day}\xa0{month}\xa0{year}","yesterday","today","tomorrow"],"global_delete":"Delete","global_error":"Error","global_error_occured":"An error occurred","global_friends":"Friends","global_hours_ago":["","%s hour ago","%s hours ago"],"global_just_now":"just now","global_mins_ago":["","%s minute ago","%s minutes ago"],"global_money_amount_rub":["","%s ruble","%s rubles"],"global_news_search_results":"Search results by news","global_photo_full_size":"View photos","global_recaptcha_title":"Confirm action","global_save":"Save","global_search_not_found":"Your search for {search} returned no results.","global_secs_ago":["","%s second ago","%s seconds ago"],"global_short_date":["","{month} {day}","yesterday","today","tomorrow"],"global_short_date_time":["","{day} {month} at {hour}:{minute} {am_pm}","yesterday at {hour}:{minute} {am_pm}","today at {hour}:{minute} {am_pm}","tomorrow at {hour}:{minute} {am_pm}"],"global_short_date_time_l":["","{day} {month} at {hour}:{minute} {am_pm}","yesterday at {hour}:{minute} {am_pm}","today at {hour}:{minute} {am_pm}","tomorrow at {hour}:{minute} {am_pm}"],"global_show_all_results":"Show all results","global_to_top":"Go up","global_unknown_error":"Unknown error","global_user_is_online":"online","global_user_is_online_mobile":"online from mobile","global_word_hours_ago":["","one hour ago","two hours ago","three hours ago","four hours ago","five hours ago"],"global_word_mins_ago":["","one minute ago","two minutes ago","three minutes ago","4 minutes ago","5 minutes ago"],"global_word_secs_ago":["","one second ago","two seconds ago","three seconds ago","four seconds ago","five seconds ago"],"head_search_results":"Search results","mail_money_transfer_cancel_btn":"Cancel transfer","mail_money_transfer_cancel_confirm":"Are you sure you want to cancel the money transfer?","mail_money_transfer_decline_btn":"Decline","mail_money_transfer_decline_confirm":"Are you sure you want to decline the money transfer?","months_of":{"1":"January","2":"February","3":"March","4":"April","5":"May","6":"June","7":"July","8":"August","9":"September","10":"October","11":"November","12":"December"},"months_sm_of":{"1":"Jan","2":"Feb","3":"Mar","4":"Apr","5":"May","6":"Jun","7":"Jul","8":"Aug","9":"Sep","10":"Oct","11":"Nov","12":"Dec"},"news_fb_money_transfer_decline_btn":"Decline","news_fb_money_transfer_decline_confirm":"Are you sure you want to decline the money transfer?","stories_bad_browser":"Stories are not supported by your browser","stories_mask_sent":"Mask sent to phone","text_N_symbols_remain":["","%s character remaining","%s characters remaining"],"text_exceeds_symbol_limit":["","You have exceeded the limit by %s character.","You have exceeded the limit by %s characters."],"votes_flex":["","vote","votes"]}},"templates":{"_":"_","audio_bits_to_cls":"{\\"1\\":\\"audio_has_lyrics\\",\\"2\\":\\"audio_can_add\\",\\"4\\":\\"audio_claimed\\",\\"8\\":\\"audio_from_queue\\",\\"16\\":\\"audio_hq\\",\\"1024\\":\\"audio_explicit\\",\\"32\\":\\"audio_lpb\\",\\"64\\":\\"audio_has_thumb\\",\\"256\\":\\"audio_moder_claimed\\",\\"2048\\":\\"audio_focus\\",\\"4096\\":\\"audio_module_wide\\"}"}}'
```

This appears to happen for offsets 11339 to 11348 (inclusive). 11349 and higher is fine again. I would like to test this in a browser (to see what VK's JS does with this), but scrolling that far takes a pretty long time...

**Comment by JustAnotherArchivist** [comment]
According to <https://vk.com/blank.php?block=119910902>, this is some sort of geoblocking:

> This page has been blocked for your country.

It appears that this is one particular post; the response indicates it might be an audio track. Based on iterating over offsets individually, this seems to be between posts 2130188 and 2130577, but I didn't try to narrow it down further.
