### ISSUE TITLE
Still getting bug when trying to scrape after Twitter reverted change

### ISSUE THREAD

**Issue by LukeNorris96** [JustAnotherArchivist/snscrape#682]
### Describe the bug

I'm still getting error messages when running a simple code after the reverted changes from Twitter. 

### How to reproduce

```python3
import snscrape.modules.twitter as sntwitter
import pandas as pd

query = 'Food'
tweets = []
limit = 100

for tweet in sntwitter.TwitterSearchScraper(query).get_items():

    #print(vars(tweet))
    #break
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.user.username, tweet.user.followersCount, tweet.coordinates, tweet.place, tweet.likeCount, tweet.retweetCount, tweet.content])

    df = pd.DataFrame(tweets, columns=['Date', 'User', 'Followers', 'Coordinates', 'Place', 'Likes', 'Retweets', 'Tweet'])
    print(df)

df.to_csv('LIWCTest.csv')
```

### Expected behavior

Should scrape most recent tweets containing the word 'food' and then break when it reaches 100 tweets. Just using this as a test. 

### Screenshots and recordings

```
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=Food&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: non-200 status code
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=Food&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
Traceback (most recent call last):
  File "/Users/luke/PycharmProjects/pythonProject/webscrapetweetTEST.py", line 8, in <module>
    for tweet in sntwitter.TwitterSearchScraper(query).get_items():
  File "/Users/luke/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 680, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', params, paginationParams, cursor = self._cursor):
  File "/Users/luke/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 369, in _iter_api_data
    obj = self._get_api_data(endpoint, reqParams)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 339, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/snscrape/base.py", line 216, in _get
    return self._request('GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/luke/PycharmProjects/pythonProject/venv/lib/python3.11/site-packages/snscrape/base.py", line 212, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=Food&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel failed, giving up.
```

### OS / Distro

MacOS 12.5 - Monterey 

### Output from `snscrape --version`

Not sure what to put here.

### Scraper

See above - Twitter 

### How are you using snscrape?

CLI

**Comment by JustAnotherArchivist** [comment]
Missing the snscrape version, but I can already tell from the error message that you're using an outdated version of snscrape.

**Comment by LukeNorris96** [comment]
Thanks :)
