### ISSUE TITLE
KeyError rest_id on retweets of suspended accounts

### ISSUE THREAD

**Issue by oshitspecialist** [JustAnotherArchivist/snscrape#828]
### Describe the bug

The program is encountering a KeyError when trying to scrape tweets using the snscrape library. The error message indicates that the 'rest_id' key is missing from the result dictionary, which is causing the program to crash while running code in python profilescraper. This problem started in the last day. This code was running into a seperate problem but it was more manageable. 

```
file "/home/jtully/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1411, in _graphql_timeline_tweet_item_result_to_tweet
    userId = int(result['core']['user_results']['result']['rest_id'])
KeyError: 'rest_id'
```

### How to reproduce

I'm running a python script that has run. Here are several Twitter Id's that have triggered it. I can share more. 

1214337422034657280
1375674533529718785
1573337918642462721

```python3
import os
from datetime import datetime
import logging

log_filename = 'tweets_log3.csv'
terminal_output_filename = 'terminal_output3.txt'
logging.basicConfig(level = logging.DEBUG)

# Check if terminal_output_filename exists
if os.path.exists(terminal_output_filename):
    # Get the current datetime as a string
    current_datetime_str = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')

    # Extract the terminal name
    terminal_name = os.environ.get('TERM', 'terminal')

    # Create a new terminal output filename using the terminal name and current datetime
    new_terminal_output_filename = f'{terminal_name}_Scrape3_{current_datetime_str}.txt'

    # Rename the existing terminal output file
    os.rename(terminal_output_filename, new_terminal_output_filename)
    
import snscrape.modules.twitter as sntwitter
import pandas as pd
import time
import datetime
import os

limit = 3200
log_filename = 'tweets_log.csv'
tweets_filename = '/media/jtully/Extreme SSD/Database/Scrape_Data/tweets300.csv'
user_id_filename = 'current_user_id3.txt'

with open('accounts3.txt', 'r') as f:
    accounts = [int(line.strip()) for line in f]

try:
    with open(user_id_filename, 'r') as f:
        current_user_id = int(f.read().strip())
    current_user_index = accounts.index(current_user_id) + 1
    if current_user_index >= len(accounts) - 1:
        print("All user IDs have been processed. Exiting...")
        exit()
except FileNotFoundError:
    current_user_id = accounts[0]
    current_user_index = 0

for user_id in accounts[current_user_index:]:
    print(f"Processing tweets for user ID {user_id}")
    with open(log_filename, 'a') as log_file:
        log_file.write(f"{user_id},{datetime.datetime.now()},Processing tweets for user ID {user_id}\n")
    # ... (rest of the code inside the loop) ...
    tweets = []
    skipped_tweets = []
    for tweet in sntwitter.TwitterProfileScraper(user_id).get_items():
        try:
            if len(tweets) == limit:
                break
            elif isinstance(tweet, sntwitter.Tombstone):
                continue
            tweet_dict = vars(tweet)  # Convert the tweet object to a dictionary
            if 'data' in tweet_dict and 'user' in tweet_dict['data'] and 'result' in tweet_dict['data']['user']:
                if '__typename' in tweet_dict['data']['user']['result'] and tweet_dict['data']['user']['result']['__typename'] == 'UserUnavailable':
                    print(f"User {user_id} is unavailable. Skipping...")
                    continue            
            tweets.append({
                'URL': tweet.url,
                'Date': tweet.date,
                'Tweet_Id': tweet.id,
                'Conversation_Id': tweet.conversationId,
                'Twitter_Id': tweet.user.id,
                'Influencer': tweet.user.username,
                'Twitter_Followers': tweet.user.followersCount,
                'Twitter_Following': tweet.user.friendsCount,
                'Retweeted': tweet.retweetedTweet,
                'QuoteTweeted': tweet.quotedTweet,
                'ReplyToTweet': tweet.inReplyToTweetId,
                'ReplyToUser': tweet.inReplyToUser,
                'mentionedusers': tweet.mentionedUsers,
                'ViewCount': tweet.viewCount
            })
        except AttributeError as e:
            skipped_tweets.append(tweet.id)
            with open(log_filename, 'a') as log_file:
                log_file.write(f"{user_id},{datetime.datetime.now()},Error encountered while processing tweet {tweet.id} for user ID {user_id}: {e}\n")
            continue

    if len(tweets) == 0:
        print(f"No tweets found for user ID {user_id}")
        with open(log_filename, 'a') as log_file:
            log_file.write(f"{user_id},{datetime.datetime.now()},No tweets found for user ID {user_id}\n")
        continue
    
    df = pd.DataFrame(tweets)
    df.to_csv(tweets_filename, mode='a', header=False, index=False)

    with open(log_filename, 'a') as log_file:
        log_file.write(f"{user_id},{datetime.datetime.now()},Finished processing tweets for user ID {user_id}\n")

    if skipped_tweets:
        with open(log_filename, 'a') as log_file:
            log_file.write(f"{user_id},{datetime.datetime.now()},Skipped tweets for user ID {user_id}:\n")
            log_file.write(','.join([str(t) for t in skipped_tweets]))
            log_file.write('\n')

    #print(f"Finished processing tweets for user ID {user_id}. Waiting for 1 minute before processing the next account...")
    #time.sleep(60)

    # Update the current_user_index
    current_user_index += 1
    
    # Break the loop if all user IDs have been processed
    if current_user_index >= len(accounts):
        break
    
    # Update the current_user_id for the next iteration
    current_user_id = accounts[current_user_index]

    # Save the current_user_id to the file
    with open(user_id_filename, 'w') as f:
        f.write(str(current_user_id))
```

### Expected behaviour

It would normally give me the following columns and then move on to the next id. 

```
                'URL': tweet.url,
                'Date': tweet.date,
                'Tweet_Id': tweet.id,
                'Conversation_Id': tweet.conversationId,
                'Twitter_Id': tweet.user.id,
                'Influencer': tweet.user.username,
                'Twitter_Followers': tweet.user.followersCount,
                'Twitter_Following': tweet.user.friendsCount,
                'Retweeted': tweet.retweetedTweet,
                'QuoteTweeted': tweet.quotedTweet,
                'ReplyToTweet': tweet.inReplyToTweetId,
                'ReplyToUser': tweet.inReplyToUser,
                'mentionedusers': tweet.mentionedUsers,
                'ViewCount': tweet.viewCount
```

### Operating system

Ubuntu

### Python version: output of `python3 --version`

3.10.6

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev1+g1c3a592

### Scraper

profilescraper

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Backtrace
```
Processing tweets for user ID 1214337422034657280
Traceback (most recent call last):
  File "/home/jtully/Documents/Twitter_Scrape/scrape_textfile.py", line 53, in <module>
    for tweet in sntwitter.TwitterProfileScraper(user_id).get_items():
  File "/home/jtully/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1842, in get_items
    yield from self._graphql_timeline_instructions_to_tweets(instructions)
  File "/home/jtully/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1456, in _graphql_timeline_instructions_to_tweets
    yield self._graphql_timeline_tweet_item_result_to_tweet(entry['content']['itemContent']['tweet_results']['result'], tweetId = tweetId)
  File "/home/jtully/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1416, in _graphql_timeline_tweet_item_result_to_tweet
    kwargs['retweetedTweet'] = self._graphql_timeline_tweet_item_result_to_tweet(tweet['retweeted_status_result']['result'])
  File "/home/jtully/.local/lib/python3.10/site-packages/snscrape/modules/twitter.py", line 1411, in _graphql_timeline_tweet_item_result_to_tweet
    userId = int(result['core']['user_results']['result']['rest_id'])
KeyError: 'rest_id'
```

### Log output

[tweets_log5.csv](https://github.com/JustAnotherArchivist/snscrape/files/11165126/tweets_log5.csv)
[xterm-256color_Scrape4_2023-04-05_19-02-08.txt](https://github.com/JustAnotherArchivist/snscrape/files/11165150/xterm-256color_Scrape4_2023-04-05_19-02-08.txt)

**Comment by JustAnotherArchivist** [comment]
Looks like this happens on retweets of suspended accounts. For the three example users given, that's 1589889021983215622, 1592471817566158854, and 1576199195811540993, respectively.

**Comment by thiago-paim** [comment]
Ran into the same error today. You can reproduce it with this snippet (the error will happen after tweet `1611027445385396227`, from 2023-01-05):
```
username = "bolsonarosp"
tweet_scrapper = sntwitter.TwitterProfileScraper(username).get_items()
tweets = []
for tweet in tweet_scrapper:
    tweets.append(tweet)
    print(tweet.id, tweet.date)
```

After some debugging, I found a way to handle the error by adding an extra check on `_graphql_timeline_tweet_item_result_to_tweet`, and will open a PR soon.
