### ISSUE TITLE
Error retrieving tweets from more than 9 twitter account handles

### ISSUE THREAD

**Issue by IliaZolas** [JustAnotherArchivist/snscrape#840]
### Describe the bug

I am loading a bunch of twitter handles of South African rock bands into an array to cycle through and retrieve their latest post within a given time period. 

Currently, if I have more than 9 handles within the accounts array, I will experience an error.

```

accounts = ["WeBeFTG", "BlackCatBonesSA","RedHelenBand","DirtyMoonshine", "VulvodyniaSlam", "OneDaySky", "SDOrgyMusic", "ccband", "Riddlebreak"]

# Query parameters
most_recent_date = datetime.datetime.now().strftime('%Y-%m-%d')
since_date = '2018-01-01'
query = " OR ".join(["(from:{} since:{} until:{})".format(account, since_date, most_recent_date) for account in accounts])

# Scrape tweets
tweets = []
for account in accounts:
    for tweet in sntwitter.TwitterSearchScraper(query).get_items():
        if tweet.user.username == account:
            # Fetch user profile picture url
            user = sntwitter.TwitterUserScraper(tweet.user.id).get_items()
            profile_pic_url = user.profileImageUrl if isinstance(user, sntwitter.User) else None

            # Check for attached media
            media_url = None
            if tweet.media:
                for media in tweet.media:
                    if isinstance(media, sntwitter.Photo):
                        media_url = media.fullUrl

            # Append tweet information to list
            tweets.append([tweet.date, tweet.user.username, tweet.content, tweet.url, media_url])

            break

# Convert to DataFrame
df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet', 'Tweet Link', 'Image URL'])
```

### How to reproduce

Attempt to cycle through an array that contains more than 9 twitter handles

### Expected behaviour

Tweet content is scraped even if cycling through an array of over 9 twitter handles.

### Operating system

macOs Big Sur

### Python version: output of `python3 --version`

Python 3.11.3

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230320

### Scraper

twitter

### How are you using snscrape?

Module (`import snscrape.modules.something` in Python code)

### Backtrace

```
Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=%28from%3AWeBeFTG+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ABlackCatBonesSA+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ARedHelenBand+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ADirtyMoonshine+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AVulvodyniaSlam+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AOneDaySky+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ASDOrgyMusic+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3Accband+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ARiddlebreak+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AIliaZolas+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ADeitysMuse+since%3A2018-01-01+until%3A2023-04-20%29&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: non-200 status code (400)
4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=%28from%3AWeBeFTG+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ABlackCatBonesSA+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ARedHelenBand+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ADirtyMoonshine+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AVulvodyniaSlam+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AOneDaySky+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ASDOrgyMusic+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3Accband+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ARiddlebreak+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AIliaZolas+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ADeitysMuse+since%3A2018-01-01+until%3A2023-04-20%29&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
Errors: non-200 status code (400), non-200 status code (400), non-200 status code (400), non-200 status code (400)
Traceback (most recent call last):
  File "/Users/iliazolas/code/IliaZolas/python-rma/Scraper/tweets-pause.py", line 21, in <module>
    for tweet in sntwitter.TwitterSearchScraper(query).get_items():
  File "/usr/local/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 1661, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "/usr/local/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 761, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/snscrape/modules/twitter.py", line 727, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/snscrape/base.py", line 251, in _get
    return self._request('GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/snscrape/base.py", line 247, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=%28from%3AWeBeFTG+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ABlackCatBonesSA+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ARedHelenBand+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ADirtyMoonshine+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AVulvodyniaSlam+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AOneDaySky+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ASDOrgyMusic+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3Accband+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ARiddlebreak+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3AIliaZolas+since%3A2018-01-01+until%3A2023-04-20%29+OR+%28from%3ADeitysMuse+since%3A2018-01-01+until%3A2023-04-20%29&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
```

**Comment by IliaZolas** [comment]
FYI - Works as expected if array contains 9 or less handles

**Comment by MrCabss69** [comment]
Same here, and no error reported scrapping > 10k tweets on a single account, only when scrapping multiple users

**Comment by johnkenjobs** [comment]
hi i got an error when trying to search 2 username anyone else encountered same issue
i am using snscrape==0.6.2.20230320

**Comment by johnkenjobs** [comment]
import snscrape.modules.twitter as sntwitter
import pandas as pd
from datetime import datetime

# get current date and time
now = datetime.now()

# prompt user for input
usernames = input("Enter the Twitter usernames you want to search for (separated by spaces): ")
keywords = input("Enter the keywords you want to search for (separated by spaces): ")
start_date = input(f"Enter the start date in YYYY-MM-DD format (default is {now.strftime('%Y-%m-%d')}): ")
end_date = input("Enter the end date in YYYY-MM-DD format (default is today): ")

# set default start date to today if not provided
if not start_date:
    start_date = now.strftime('%Y-%m-%d')

# set default end date to today if not provided
if not end_date:
    end_date = now.strftime('%Y-%m-%d')

# format query
usernames_list = usernames.split()
query = f"({' OR '.join(keywords.split())}) (from:{' OR from:'.join(usernames_list)}) until:{end_date} since:{start_date}"
tweets = []
limit = 5000

for tweet in sntwitter.TwitterSearchScraper(query).get_items():
    if len(tweets) == limit:
        break
    else:
        tweets.append([tweet.date, tweet.user.username, tweet.rawContent, tweet.url])

df = pd.DataFrame(tweets, columns=['Date', 'User', 'Tweet', 'URL'])
df['URL'] = df['URL'].apply(lambda x: '<a href="{}" target="_blank">Link</a>'.format(x))
html_output = df.to_html(escape=False)

with open('tweets.html', 'w') as f:
    f.write(html_output)

**Comment by JustAnotherArchivist** [comment]
That original query works fine for me, but in general: #843

**Comment by JustAnotherArchivist** [comment]
Also, the query already covers all accounts. You don't need to loop over the accounts again and filter by account. That just means you're running the same search 9 times...
