### ISSUE TITLE
CRITICAL  snscrape.base  Errors: blocked (404), blocked (404), blocked (404), blocked (404)

### ISSUE THREAD

**Issue by kevin0107** [JustAnotherArchivist/snscrape#878]
### Describe the bug

2023-05-04 10:16:05.284  ERROR  snscrape.base  Error retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Atextfiles&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe: blocked (404)
2023-05-04 10:16:05.284  CRITICAL  snscrape.base  4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Atextfiles&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.
2023-05-04 10:16:05.284  CRITICAL  snscrape.base  Errors: blocked (404), blocked (404), blocked (404), blocked (404)
2023-05-04 10:16:05.318  CRITICAL  snscrape._cli  Dumped stack and locals to /var/folders/wv/zv0m008n0fb47s7dn_xprdj80000gn/T/snscrape_locals_q8xe9hkg
Traceback (most recent call last):
  File "/Users/shijian/miniconda3/bin/snscrape", line 8, in <module>
    sys.exit(main())
  File "/Users/shijian/miniconda3/lib/python3.9/site-packages/snscrape/_cli.py", line 320, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "/Users/shijian/miniconda3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 1755, in get_items
    yield from super().get_items()
  File "/Users/shijian/miniconda3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 1661, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "/Users/shijian/miniconda3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 762, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
  File "/Users/shijian/miniconda3/lib/python3.9/site-packages/snscrape/modules/twitter.py", line 728, in _get_api_data
    r = self._get(endpoint, params = params, headers = self._apiHeaders, responseOkCallback = self._check_api_response)
  File "/Users/shijian/miniconda3/lib/python3.9/site-packages/snscrape/base.py", line 251, in _get
    return self._request('GET', *args, **kwargs)
  File "/Users/shijian/miniconda3/lib/python3.9/site-packages/snscrape/base.py", line 247, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3Atextfiles&tweet_search_mode=live&count=20&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe failed, giving up.

### How to reproduce

terminal run   snscrape twitter-user textfiles

### Expected behaviour

terminal run   snscrape twitter-user textfiles

### Operating system

MacOS 13.3.1 (a) 

### Python version: output of `python3 --version`

Python 3.9.12

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230321.dev3+g3dd9c28

### Scraper

snscrape twitter-user textfiles

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

**Comment by JustAnotherArchivist** [comment]
#783
