### ISSUE TITLE
ConnectionResetError

### ISSUE THREAD

**Issue by 19barsav** [JustAnotherArchivist/snscrape#935]
### Describe the bug

I have a ConnectionResetError no matter the CLI twitter command I run. I just installed and updated everything. Some research says that Python is expecting a different header, but I don't believe that's changeable from a user side. If I use m personal laptop, I get @931 so I can't tell if it's me or not. 

### How to reproduce

`snscrape twitter-user textfiles`

### Expected behaviour

Should be scraping and displaying results. 

### Operating system

Windows 10

### Python version: output of `python3 --version`

Python 3.11.3

### snscrape version: output of `snscrape --version`

snscrape 0.6.2.20230320

### Scraper

twitter-user

### How are you using snscrape?

CLI (`snscrape ...` as a command, e.g. in a terminal)

### Backtrace

(twitter_env) C:\>snscrape twitter-user textfiles
2023-05-31 12:41:56.868  ERROR  snscrape.base  Error retrieving https://twitter.com/textfiles: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
2023-05-31 12:41:56.869  CRITICAL  snscrape.base  4 requests to https://twitter.com/textfiles failed, giving up.
2023-05-31 12:41:56.869  CRITICAL  snscrape.base  Errors: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
2023-05-31 12:41:57.304  CRITICAL  snscrape._cli  Dumped stack and locals to C:\Users\usks1b48\AppData\Local\Temp\snscrape_locals_0y2qkppv
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Scripts\snscrape.exe\__main__.py", line 7, in <module>
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Lib\site-packages\snscrape\_cli.py", line 320, in main
    for i, item in enumerate(scraper.get_items(), start = 1):
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Lib\site-packages\snscrape\modules\twitter.py", line 1755, in get_items
    yield from super().get_items()
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Lib\site-packages\snscrape\modules\twitter.py", line 1661, in get_items
    for obj in self._iter_api_data('https://api.twitter.com/2/search/adaptive.json', _TwitterAPIType.V2, params, paginationParams, cursor = self._cursor):
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Lib\site-packages\snscrape\modules\twitter.py", line 761, in _iter_api_data
    obj = self._get_api_data(endpoint, apiType, reqParams)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Lib\site-packages\snscrape\modules\twitter.py", line 724, in _get_api_data
    self._ensure_guest_token()
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Lib\site-packages\snscrape\modules\twitter.py", line 687, in _ensure_guest_token
    r = self._get(self._baseUrl if url is None else url, headers = {'User-Agent': self._userAgent}, responseOkCallback = self._check_guest_token_response)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Lib\site-packages\snscrape\base.py", line 251, in _get
    return self._request('GET', *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usks1b48\.conda\envs\twitter_env\Lib\site-packages\snscrape\base.py", line 247, in _request
    raise ScraperException(msg)
snscrape.base.ScraperException: 4 requests to https://twitter.com/textfiles failed, giving up.

### Log output

(twitter_env) C:\>snscrape -vv twitter-user textfiles
2023-05-31 12:52:35.578  INFO  snscrape.modules.twitter  Retrieving scroll page None
2023-05-31 12:52:35.578  DEBUG  filelock  Attempting to acquire lock 2108678770256 on C:\Users\usks1b48\.cache\snscrape\cli-twitter-guest-token.json.lock
2023-05-31 12:52:35.581  DEBUG  filelock  Lock 2108678770256 acquired on C:\Users\usks1b48\.cache\snscrape\cli-twitter-guest-token.json.lock
2023-05-31 12:52:35.583  DEBUG  filelock  Attempting to release lock 2108678770256 on C:\Users\usks1b48\.cache\snscrape\cli-twitter-guest-token.json.lock
2023-05-31 12:52:35.587  DEBUG  filelock  Lock 2108678770256 released on C:\Users\usks1b48\.cache\snscrape\cli-twitter-guest-token.json.lock
2023-05-31 12:52:35.587  INFO  snscrape.modules.twitter  Retrieving guest token
2023-05-31 12:52:35.599  INFO  snscrape.base  Retrieving https://twitter.com/textfiles
2023-05-31 12:52:35.599  DEBUG  snscrape.base  ... with headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.2225 Safari/537.16'}
2023-05-31 12:52:35.599  DEBUG  snscrape.base  ... with environmentSettings: {'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
2023-05-31 12:52:35.602  DEBUG  urllib3.connectionpool  Starting new HTTPS connection (1): twitter.com:443
2023-05-31 12:52:35.797  INFO  snscrape.base  Error retrieving https://twitter.com/textfiles: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), retrying
2023-05-31 12:52:35.797  INFO  snscrape.base  Waiting 1 seconds
2023-05-31 12:52:36.801  INFO  snscrape.base  Retrieving https://twitter.com/textfiles
2023-05-31 12:52:36.801  DEBUG  snscrape.base  ... with headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.2225 Safari/537.16'}
2023-05-31 12:52:36.805  DEBUG  snscrape.base  ... with environmentSettings: {'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
2023-05-31 12:52:36.813  DEBUG  urllib3.connectionpool  Starting new HTTPS connection (2): twitter.com:443
2023-05-31 12:52:36.964  INFO  snscrape.base  Error retrieving https://twitter.com/textfiles: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), retrying
2023-05-31 12:52:36.964  INFO  snscrape.base  Waiting 2 seconds
2023-05-31 12:52:38.970  INFO  snscrape.base  Retrieving https://twitter.com/textfiles
2023-05-31 12:52:38.971  DEBUG  snscrape.base  ... with headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.2225 Safari/537.16'}
2023-05-31 12:52:38.980  DEBUG  snscrape.base  ... with environmentSettings: {'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
2023-05-31 12:52:38.982  DEBUG  urllib3.connectionpool  Starting new HTTPS connection (3): twitter.com:443
2023-05-31 12:52:39.135  INFO  snscrape.base  Error retrieving https://twitter.com/textfiles: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), retrying
2023-05-31 12:52:39.146  INFO  snscrape.base  Waiting 4 seconds
2023-05-31 12:52:43.152  INFO  snscrape.base  Retrieving https://twitter.com/textfiles
2023-05-31 12:52:43.152  DEBUG  snscrape.base  ... with headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.5563.2225 Safari/537.16'}
2023-05-31 12:52:43.162  DEBUG  snscrape.base  ... with environmentSettings: {'proxies': OrderedDict(), 'stream': False, 'verify': True, 'cert': None}
2023-05-31 12:52:43.164  DEBUG  urllib3.connectionpool  Starting new HTTPS connection (4): twitter.com:443
2023-05-31 12:52:43.319  ERROR  snscrape.base  Error retrieving https://twitter.com/textfiles: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
2023-05-31 12:52:43.320  CRITICAL  snscrape.base  4 requests to https://twitter.com/textfiles failed, giving up.
2023-05-31 12:52:43.328  CRITICAL  snscrape.base  Errors: ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))), ConnectionError(ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
2023-05-31 12:52:43.790  CRITICAL  snscrape._cli  Dumped stack and locals to C:\Users\usks1b48\AppData\Local\Temp\snscrape_locals_bwmos2z1

### Additional context

I am in a conda environment :)

**Comment by 19barsav** [comment]
99% sure it is our own proxy blocking it, but I wanted to make sure before I escalate it with IT.

**Comment by JustAnotherArchivist** [comment]
This definitely sounds like a proxy issue, yes. I've never seen Twitter reproducibly abort connections (though it can happen randomly and rarely, of course).

**Comment by 19barsav** [comment]
Thank you! I'll escalate the issue :)
